/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RegisterImport } from './routes/register'
import { Route as LoginImport } from './routes/login'
import { Route as AboutImport } from './routes/about'
import { Route as AuthenticatedadminImport } from './routes/_authenticated_admin'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as TentangKamiIndexImport } from './routes/tentang-kami/index'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as AuthenticatedProfileImport } from './routes/_authenticated/profile'
import { Route as TentangKamiApaItuAdopsiPohonIndexImport } from './routes/tentang-kami/apa-itu-adopsi-pohon/index'
import { Route as AuthenticatedadminAdminIndexImport } from './routes/_authenticated_admin/admin/index'
import { Route as AuthenticatedProgramKamiIndexImport } from './routes/_authenticated/program-kami/index'
import { Route as AuthenticatedadminAdminProfileImport } from './routes/_authenticated_admin/admin/profile'
import { Route as AuthenticatedTentangKamiKelompokKomunitasIndexImport } from './routes/_authenticated/tentang-kami/kelompok-komunitas/index'
import { Route as AuthenticatedProgramKamiPemberdayaanMasyarakatIndexImport } from './routes/_authenticated/program-kami/pemberdayaan-masyarakat/index'
import { Route as AuthenticatedProgramKamiPatroliGeoTaggingIndexImport } from './routes/_authenticated/program-kami/patroli-&-geo-tagging/index'
import { Route as AuthenticatedProgramKamiMonitorBiodiversityIndexImport } from './routes/_authenticated/program-kami/monitor-biodiversity/index'
import { Route as AuthenticatedProgramKamiAdopsiPohonIndexImport } from './routes/_authenticated/program-kami/adopsi-pohon/index'
import { Route as AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasNameImport } from './routes/_authenticated/tentang-kami/kelompok-komunitas/$kelompokKomunitasName'
import { Route as AuthenticatedadminAdminTentangKamiKelompokKomunitasIndexImport } from './routes/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/index'
import { Route as AuthenticatedadminAdminMasterPohonIndexImport } from './routes/_authenticated_admin/admin/master/pohon/index'
import { Route as AuthenticatedadminAdminDataPohonIndexImport } from './routes/_authenticated_admin/admin/data/pohon/index'
import { Route as AuthenticatedadminAdminConfigUserIndexImport } from './routes/_authenticated_admin/admin/config/user/index'
import { Route as AuthenticatedadminAdminConfigRolePermissionIndexImport } from './routes/_authenticated_admin/admin/config/role-permission/index'
import { Route as AuthenticatedadminAdminTentangKamiKelompokKomunitasAddKomunitasImport } from './routes/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/add-komunitas'
import { Route as AuthenticatedadminAdminMasterPohonAddMasterTreeImport } from './routes/_authenticated_admin/admin/master/pohon/add-master-tree'
import { Route as AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdIndexImport } from './routes/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/index'
import { Route as AuthenticatedadminAdminDataPohonAddIndexImport } from './routes/_authenticated_admin/admin/data/pohon/add/index'
import { Route as AuthenticatedadminAdminDataPohonTreeIdIndexImport } from './routes/_authenticated_admin/admin/data/pohon/$treeId/index'
import { Route as AuthenticatedadminAdminConfigUserAddIndexImport } from './routes/_authenticated_admin/admin/config/user/add/index'
import { Route as AuthenticatedadminAdminMasterPohonUpdateMasterTreeIdImport } from './routes/_authenticated_admin/admin/master/pohon/update/$masterTreeId'
import { Route as AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdUpdateKomunitasIndexImport } from './routes/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/update-komunitas/index'
import { Route as AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAllPhotosIndexImport } from './routes/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/all-photos/index'
import { Route as AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasIndexImport } from './routes/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/index'
import { Route as AuthenticatedadminAdminDataPohonTreeIdUpdateIndexImport } from './routes/_authenticated_admin/admin/data/pohon/$treeId/update/index'
import { Route as AuthenticatedadminAdminDataPohonTreeIdSurveyHistoryIndexImport } from './routes/_authenticated_admin/admin/data/pohon/$treeId/survey-history/index'
import { Route as AuthenticatedadminAdminConfigUserUserIdUpdateIndexImport } from './routes/_authenticated_admin/admin/config/user/$userId/update/index'
import { Route as AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasAddIndexImport } from './routes/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/add/index'
import { Route as AuthenticatedadminAdminDataPohonTreeIdSurveyHistoryAddIndexImport } from './routes/_authenticated_admin/admin/data/pohon/$treeId/survey-history/add/index'
import { Route as AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasGroupActivityIdUpdateIndexImport } from './routes/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/$groupActivityId/update/index'
import { Route as AuthenticatedadminAdminDataPohonTreeIdSurveyHistorySurveyHistoryIdUpdateIndexImport } from './routes/_authenticated_admin/admin/data/pohon/$treeId/survey-history/$surveyHistoryId/update/index'

// Create/Update Routes

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedadminRoute = AuthenticatedadminImport.update({
  id: '/_authenticated_admin',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const TentangKamiIndexRoute = TentangKamiIndexImport.update({
  id: '/tentang-kami/',
  path: '/tentang-kami/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedProfileRoute = AuthenticatedProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const TentangKamiApaItuAdopsiPohonIndexRoute =
  TentangKamiApaItuAdopsiPohonIndexImport.update({
    id: '/tentang-kami/apa-itu-adopsi-pohon/',
    path: '/tentang-kami/apa-itu-adopsi-pohon/',
    getParentRoute: () => rootRoute,
  } as any)

const AuthenticatedadminAdminIndexRoute =
  AuthenticatedadminAdminIndexImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => AuthenticatedadminRoute,
  } as any)

const AuthenticatedProgramKamiIndexRoute =
  AuthenticatedProgramKamiIndexImport.update({
    id: '/program-kami/',
    path: '/program-kami/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedadminAdminProfileRoute =
  AuthenticatedadminAdminProfileImport.update({
    id: '/admin/profile',
    path: '/admin/profile',
    getParentRoute: () => AuthenticatedadminRoute,
  } as any)

const AuthenticatedTentangKamiKelompokKomunitasIndexRoute =
  AuthenticatedTentangKamiKelompokKomunitasIndexImport.update({
    id: '/tentang-kami/kelompok-komunitas/',
    path: '/tentang-kami/kelompok-komunitas/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedProgramKamiPemberdayaanMasyarakatIndexRoute =
  AuthenticatedProgramKamiPemberdayaanMasyarakatIndexImport.update({
    id: '/program-kami/pemberdayaan-masyarakat/',
    path: '/program-kami/pemberdayaan-masyarakat/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedProgramKamiPatroliGeoTaggingIndexRoute =
  AuthenticatedProgramKamiPatroliGeoTaggingIndexImport.update({
    id: '/program-kami/patroli-&-geo-tagging/',
    path: '/program-kami/patroli-&-geo-tagging/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedProgramKamiMonitorBiodiversityIndexRoute =
  AuthenticatedProgramKamiMonitorBiodiversityIndexImport.update({
    id: '/program-kami/monitor-biodiversity/',
    path: '/program-kami/monitor-biodiversity/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedProgramKamiAdopsiPohonIndexRoute =
  AuthenticatedProgramKamiAdopsiPohonIndexImport.update({
    id: '/program-kami/adopsi-pohon/',
    path: '/program-kami/adopsi-pohon/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasNameRoute =
  AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasNameImport.update({
    id: '/tentang-kami/kelompok-komunitas/$kelompokKomunitasName',
    path: '/tentang-kami/kelompok-komunitas/$kelompokKomunitasName',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedadminAdminTentangKamiKelompokKomunitasIndexRoute =
  AuthenticatedadminAdminTentangKamiKelompokKomunitasIndexImport.update({
    id: '/admin/tentang-kami/kelompok-komunitas/',
    path: '/admin/tentang-kami/kelompok-komunitas/',
    getParentRoute: () => AuthenticatedadminRoute,
  } as any)

const AuthenticatedadminAdminMasterPohonIndexRoute =
  AuthenticatedadminAdminMasterPohonIndexImport.update({
    id: '/admin/master/pohon/',
    path: '/admin/master/pohon/',
    getParentRoute: () => AuthenticatedadminRoute,
  } as any)

const AuthenticatedadminAdminDataPohonIndexRoute =
  AuthenticatedadminAdminDataPohonIndexImport.update({
    id: '/admin/data/pohon/',
    path: '/admin/data/pohon/',
    getParentRoute: () => AuthenticatedadminRoute,
  } as any)

const AuthenticatedadminAdminConfigUserIndexRoute =
  AuthenticatedadminAdminConfigUserIndexImport.update({
    id: '/admin/config/user/',
    path: '/admin/config/user/',
    getParentRoute: () => AuthenticatedadminRoute,
  } as any)

const AuthenticatedadminAdminConfigRolePermissionIndexRoute =
  AuthenticatedadminAdminConfigRolePermissionIndexImport.update({
    id: '/admin/config/role-permission/',
    path: '/admin/config/role-permission/',
    getParentRoute: () => AuthenticatedadminRoute,
  } as any)

const AuthenticatedadminAdminTentangKamiKelompokKomunitasAddKomunitasRoute =
  AuthenticatedadminAdminTentangKamiKelompokKomunitasAddKomunitasImport.update({
    id: '/admin/tentang-kami/kelompok-komunitas/add-komunitas',
    path: '/admin/tentang-kami/kelompok-komunitas/add-komunitas',
    getParentRoute: () => AuthenticatedadminRoute,
  } as any)

const AuthenticatedadminAdminMasterPohonAddMasterTreeRoute =
  AuthenticatedadminAdminMasterPohonAddMasterTreeImport.update({
    id: '/admin/master/pohon/add-master-tree',
    path: '/admin/master/pohon/add-master-tree',
    getParentRoute: () => AuthenticatedadminRoute,
  } as any)

const AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdIndexRoute =
  AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdIndexImport.update(
    {
      id: '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/',
      path: '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/',
      getParentRoute: () => AuthenticatedadminRoute,
    } as any,
  )

const AuthenticatedadminAdminDataPohonAddIndexRoute =
  AuthenticatedadminAdminDataPohonAddIndexImport.update({
    id: '/admin/data/pohon/add/',
    path: '/admin/data/pohon/add/',
    getParentRoute: () => AuthenticatedadminRoute,
  } as any)

const AuthenticatedadminAdminDataPohonTreeIdIndexRoute =
  AuthenticatedadminAdminDataPohonTreeIdIndexImport.update({
    id: '/admin/data/pohon/$treeId/',
    path: '/admin/data/pohon/$treeId/',
    getParentRoute: () => AuthenticatedadminRoute,
  } as any)

const AuthenticatedadminAdminConfigUserAddIndexRoute =
  AuthenticatedadminAdminConfigUserAddIndexImport.update({
    id: '/admin/config/user/add/',
    path: '/admin/config/user/add/',
    getParentRoute: () => AuthenticatedadminRoute,
  } as any)

const AuthenticatedadminAdminMasterPohonUpdateMasterTreeIdRoute =
  AuthenticatedadminAdminMasterPohonUpdateMasterTreeIdImport.update({
    id: '/admin/master/pohon/update/$masterTreeId',
    path: '/admin/master/pohon/update/$masterTreeId',
    getParentRoute: () => AuthenticatedadminRoute,
  } as any)

const AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdUpdateKomunitasIndexRoute =
  AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdUpdateKomunitasIndexImport.update(
    {
      id: '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/update-komunitas/',
      path: '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/update-komunitas/',
      getParentRoute: () => AuthenticatedadminRoute,
    } as any,
  )

const AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAllPhotosIndexRoute =
  AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAllPhotosIndexImport.update(
    {
      id: '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/all-photos/',
      path: '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/all-photos/',
      getParentRoute: () => AuthenticatedadminRoute,
    } as any,
  )

const AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasIndexRoute =
  AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasIndexImport.update(
    {
      id: '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/',
      path: '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/',
      getParentRoute: () => AuthenticatedadminRoute,
    } as any,
  )

const AuthenticatedadminAdminDataPohonTreeIdUpdateIndexRoute =
  AuthenticatedadminAdminDataPohonTreeIdUpdateIndexImport.update({
    id: '/admin/data/pohon/$treeId/update/',
    path: '/admin/data/pohon/$treeId/update/',
    getParentRoute: () => AuthenticatedadminRoute,
  } as any)

const AuthenticatedadminAdminDataPohonTreeIdSurveyHistoryIndexRoute =
  AuthenticatedadminAdminDataPohonTreeIdSurveyHistoryIndexImport.update({
    id: '/admin/data/pohon/$treeId/survey-history/',
    path: '/admin/data/pohon/$treeId/survey-history/',
    getParentRoute: () => AuthenticatedadminRoute,
  } as any)

const AuthenticatedadminAdminConfigUserUserIdUpdateIndexRoute =
  AuthenticatedadminAdminConfigUserUserIdUpdateIndexImport.update({
    id: '/admin/config/user/$userId/update/',
    path: '/admin/config/user/$userId/update/',
    getParentRoute: () => AuthenticatedadminRoute,
  } as any)

const AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasAddIndexRoute =
  AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasAddIndexImport.update(
    {
      id: '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/add/',
      path: '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/add/',
      getParentRoute: () => AuthenticatedadminRoute,
    } as any,
  )

const AuthenticatedadminAdminDataPohonTreeIdSurveyHistoryAddIndexRoute =
  AuthenticatedadminAdminDataPohonTreeIdSurveyHistoryAddIndexImport.update({
    id: '/admin/data/pohon/$treeId/survey-history/add/',
    path: '/admin/data/pohon/$treeId/survey-history/add/',
    getParentRoute: () => AuthenticatedadminRoute,
  } as any)

const AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasGroupActivityIdUpdateIndexRoute =
  AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasGroupActivityIdUpdateIndexImport.update(
    {
      id: '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/$groupActivityId/update/',
      path: '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/$groupActivityId/update/',
      getParentRoute: () => AuthenticatedadminRoute,
    } as any,
  )

const AuthenticatedadminAdminDataPohonTreeIdSurveyHistorySurveyHistoryIdUpdateIndexRoute =
  AuthenticatedadminAdminDataPohonTreeIdSurveyHistorySurveyHistoryIdUpdateIndexImport.update(
    {
      id: '/admin/data/pohon/$treeId/survey-history/$surveyHistoryId/update/',
      path: '/admin/data/pohon/$treeId/survey-history/$surveyHistoryId/update/',
      getParentRoute: () => AuthenticatedadminRoute,
    } as any,
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated_admin': {
      id: '/_authenticated_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedadminImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/tentang-kami/': {
      id: '/tentang-kami/'
      path: '/tentang-kami'
      fullPath: '/tentang-kami'
      preLoaderRoute: typeof TentangKamiIndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated_admin/admin/profile': {
      id: '/_authenticated_admin/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AuthenticatedadminAdminProfileImport
      parentRoute: typeof AuthenticatedadminImport
    }
    '/_authenticated/program-kami/': {
      id: '/_authenticated/program-kami/'
      path: '/program-kami'
      fullPath: '/program-kami'
      preLoaderRoute: typeof AuthenticatedProgramKamiIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated_admin/admin/': {
      id: '/_authenticated_admin/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedadminAdminIndexImport
      parentRoute: typeof AuthenticatedadminImport
    }
    '/tentang-kami/apa-itu-adopsi-pohon/': {
      id: '/tentang-kami/apa-itu-adopsi-pohon/'
      path: '/tentang-kami/apa-itu-adopsi-pohon'
      fullPath: '/tentang-kami/apa-itu-adopsi-pohon'
      preLoaderRoute: typeof TentangKamiApaItuAdopsiPohonIndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/tentang-kami/kelompok-komunitas/$kelompokKomunitasName': {
      id: '/_authenticated/tentang-kami/kelompok-komunitas/$kelompokKomunitasName'
      path: '/tentang-kami/kelompok-komunitas/$kelompokKomunitasName'
      fullPath: '/tentang-kami/kelompok-komunitas/$kelompokKomunitasName'
      preLoaderRoute: typeof AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasNameImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/program-kami/adopsi-pohon/': {
      id: '/_authenticated/program-kami/adopsi-pohon/'
      path: '/program-kami/adopsi-pohon'
      fullPath: '/program-kami/adopsi-pohon'
      preLoaderRoute: typeof AuthenticatedProgramKamiAdopsiPohonIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/program-kami/monitor-biodiversity/': {
      id: '/_authenticated/program-kami/monitor-biodiversity/'
      path: '/program-kami/monitor-biodiversity'
      fullPath: '/program-kami/monitor-biodiversity'
      preLoaderRoute: typeof AuthenticatedProgramKamiMonitorBiodiversityIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/program-kami/patroli-&-geo-tagging/': {
      id: '/_authenticated/program-kami/patroli-&-geo-tagging/'
      path: '/program-kami/patroli-&-geo-tagging'
      fullPath: '/program-kami/patroli-&-geo-tagging'
      preLoaderRoute: typeof AuthenticatedProgramKamiPatroliGeoTaggingIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/program-kami/pemberdayaan-masyarakat/': {
      id: '/_authenticated/program-kami/pemberdayaan-masyarakat/'
      path: '/program-kami/pemberdayaan-masyarakat'
      fullPath: '/program-kami/pemberdayaan-masyarakat'
      preLoaderRoute: typeof AuthenticatedProgramKamiPemberdayaanMasyarakatIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/tentang-kami/kelompok-komunitas/': {
      id: '/_authenticated/tentang-kami/kelompok-komunitas/'
      path: '/tentang-kami/kelompok-komunitas'
      fullPath: '/tentang-kami/kelompok-komunitas'
      preLoaderRoute: typeof AuthenticatedTentangKamiKelompokKomunitasIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated_admin/admin/master/pohon/add-master-tree': {
      id: '/_authenticated_admin/admin/master/pohon/add-master-tree'
      path: '/admin/master/pohon/add-master-tree'
      fullPath: '/admin/master/pohon/add-master-tree'
      preLoaderRoute: typeof AuthenticatedadminAdminMasterPohonAddMasterTreeImport
      parentRoute: typeof AuthenticatedadminImport
    }
    '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/add-komunitas': {
      id: '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/add-komunitas'
      path: '/admin/tentang-kami/kelompok-komunitas/add-komunitas'
      fullPath: '/admin/tentang-kami/kelompok-komunitas/add-komunitas'
      preLoaderRoute: typeof AuthenticatedadminAdminTentangKamiKelompokKomunitasAddKomunitasImport
      parentRoute: typeof AuthenticatedadminImport
    }
    '/_authenticated_admin/admin/config/role-permission/': {
      id: '/_authenticated_admin/admin/config/role-permission/'
      path: '/admin/config/role-permission'
      fullPath: '/admin/config/role-permission'
      preLoaderRoute: typeof AuthenticatedadminAdminConfigRolePermissionIndexImport
      parentRoute: typeof AuthenticatedadminImport
    }
    '/_authenticated_admin/admin/config/user/': {
      id: '/_authenticated_admin/admin/config/user/'
      path: '/admin/config/user'
      fullPath: '/admin/config/user'
      preLoaderRoute: typeof AuthenticatedadminAdminConfigUserIndexImport
      parentRoute: typeof AuthenticatedadminImport
    }
    '/_authenticated_admin/admin/data/pohon/': {
      id: '/_authenticated_admin/admin/data/pohon/'
      path: '/admin/data/pohon'
      fullPath: '/admin/data/pohon'
      preLoaderRoute: typeof AuthenticatedadminAdminDataPohonIndexImport
      parentRoute: typeof AuthenticatedadminImport
    }
    '/_authenticated_admin/admin/master/pohon/': {
      id: '/_authenticated_admin/admin/master/pohon/'
      path: '/admin/master/pohon'
      fullPath: '/admin/master/pohon'
      preLoaderRoute: typeof AuthenticatedadminAdminMasterPohonIndexImport
      parentRoute: typeof AuthenticatedadminImport
    }
    '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/': {
      id: '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/'
      path: '/admin/tentang-kami/kelompok-komunitas'
      fullPath: '/admin/tentang-kami/kelompok-komunitas'
      preLoaderRoute: typeof AuthenticatedadminAdminTentangKamiKelompokKomunitasIndexImport
      parentRoute: typeof AuthenticatedadminImport
    }
    '/_authenticated_admin/admin/master/pohon/update/$masterTreeId': {
      id: '/_authenticated_admin/admin/master/pohon/update/$masterTreeId'
      path: '/admin/master/pohon/update/$masterTreeId'
      fullPath: '/admin/master/pohon/update/$masterTreeId'
      preLoaderRoute: typeof AuthenticatedadminAdminMasterPohonUpdateMasterTreeIdImport
      parentRoute: typeof AuthenticatedadminImport
    }
    '/_authenticated_admin/admin/config/user/add/': {
      id: '/_authenticated_admin/admin/config/user/add/'
      path: '/admin/config/user/add'
      fullPath: '/admin/config/user/add'
      preLoaderRoute: typeof AuthenticatedadminAdminConfigUserAddIndexImport
      parentRoute: typeof AuthenticatedadminImport
    }
    '/_authenticated_admin/admin/data/pohon/$treeId/': {
      id: '/_authenticated_admin/admin/data/pohon/$treeId/'
      path: '/admin/data/pohon/$treeId'
      fullPath: '/admin/data/pohon/$treeId'
      preLoaderRoute: typeof AuthenticatedadminAdminDataPohonTreeIdIndexImport
      parentRoute: typeof AuthenticatedadminImport
    }
    '/_authenticated_admin/admin/data/pohon/add/': {
      id: '/_authenticated_admin/admin/data/pohon/add/'
      path: '/admin/data/pohon/add'
      fullPath: '/admin/data/pohon/add'
      preLoaderRoute: typeof AuthenticatedadminAdminDataPohonAddIndexImport
      parentRoute: typeof AuthenticatedadminImport
    }
    '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/': {
      id: '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/'
      path: '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId'
      fullPath: '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId'
      preLoaderRoute: typeof AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdIndexImport
      parentRoute: typeof AuthenticatedadminImport
    }
    '/_authenticated_admin/admin/config/user/$userId/update/': {
      id: '/_authenticated_admin/admin/config/user/$userId/update/'
      path: '/admin/config/user/$userId/update'
      fullPath: '/admin/config/user/$userId/update'
      preLoaderRoute: typeof AuthenticatedadminAdminConfigUserUserIdUpdateIndexImport
      parentRoute: typeof AuthenticatedadminImport
    }
    '/_authenticated_admin/admin/data/pohon/$treeId/survey-history/': {
      id: '/_authenticated_admin/admin/data/pohon/$treeId/survey-history/'
      path: '/admin/data/pohon/$treeId/survey-history'
      fullPath: '/admin/data/pohon/$treeId/survey-history'
      preLoaderRoute: typeof AuthenticatedadminAdminDataPohonTreeIdSurveyHistoryIndexImport
      parentRoute: typeof AuthenticatedadminImport
    }
    '/_authenticated_admin/admin/data/pohon/$treeId/update/': {
      id: '/_authenticated_admin/admin/data/pohon/$treeId/update/'
      path: '/admin/data/pohon/$treeId/update'
      fullPath: '/admin/data/pohon/$treeId/update'
      preLoaderRoute: typeof AuthenticatedadminAdminDataPohonTreeIdUpdateIndexImport
      parentRoute: typeof AuthenticatedadminImport
    }
    '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/': {
      id: '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/'
      path: '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas'
      fullPath: '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas'
      preLoaderRoute: typeof AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasIndexImport
      parentRoute: typeof AuthenticatedadminImport
    }
    '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/all-photos/': {
      id: '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/all-photos/'
      path: '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/all-photos'
      fullPath: '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/all-photos'
      preLoaderRoute: typeof AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAllPhotosIndexImport
      parentRoute: typeof AuthenticatedadminImport
    }
    '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/update-komunitas/': {
      id: '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/update-komunitas/'
      path: '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/update-komunitas'
      fullPath: '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/update-komunitas'
      preLoaderRoute: typeof AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdUpdateKomunitasIndexImport
      parentRoute: typeof AuthenticatedadminImport
    }
    '/_authenticated_admin/admin/data/pohon/$treeId/survey-history/add/': {
      id: '/_authenticated_admin/admin/data/pohon/$treeId/survey-history/add/'
      path: '/admin/data/pohon/$treeId/survey-history/add'
      fullPath: '/admin/data/pohon/$treeId/survey-history/add'
      preLoaderRoute: typeof AuthenticatedadminAdminDataPohonTreeIdSurveyHistoryAddIndexImport
      parentRoute: typeof AuthenticatedadminImport
    }
    '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/add/': {
      id: '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/add/'
      path: '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/add'
      fullPath: '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/add'
      preLoaderRoute: typeof AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasAddIndexImport
      parentRoute: typeof AuthenticatedadminImport
    }
    '/_authenticated_admin/admin/data/pohon/$treeId/survey-history/$surveyHistoryId/update/': {
      id: '/_authenticated_admin/admin/data/pohon/$treeId/survey-history/$surveyHistoryId/update/'
      path: '/admin/data/pohon/$treeId/survey-history/$surveyHistoryId/update'
      fullPath: '/admin/data/pohon/$treeId/survey-history/$surveyHistoryId/update'
      preLoaderRoute: typeof AuthenticatedadminAdminDataPohonTreeIdSurveyHistorySurveyHistoryIdUpdateIndexImport
      parentRoute: typeof AuthenticatedadminImport
    }
    '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/$groupActivityId/update/': {
      id: '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/$groupActivityId/update/'
      path: '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/$groupActivityId/update'
      fullPath: '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/$groupActivityId/update'
      preLoaderRoute: typeof AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasGroupActivityIdUpdateIndexImport
      parentRoute: typeof AuthenticatedadminImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedProgramKamiIndexRoute: typeof AuthenticatedProgramKamiIndexRoute
  AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasNameRoute: typeof AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasNameRoute
  AuthenticatedProgramKamiAdopsiPohonIndexRoute: typeof AuthenticatedProgramKamiAdopsiPohonIndexRoute
  AuthenticatedProgramKamiMonitorBiodiversityIndexRoute: typeof AuthenticatedProgramKamiMonitorBiodiversityIndexRoute
  AuthenticatedProgramKamiPatroliGeoTaggingIndexRoute: typeof AuthenticatedProgramKamiPatroliGeoTaggingIndexRoute
  AuthenticatedProgramKamiPemberdayaanMasyarakatIndexRoute: typeof AuthenticatedProgramKamiPemberdayaanMasyarakatIndexRoute
  AuthenticatedTentangKamiKelompokKomunitasIndexRoute: typeof AuthenticatedTentangKamiKelompokKomunitasIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedProgramKamiIndexRoute: AuthenticatedProgramKamiIndexRoute,
  AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasNameRoute:
    AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasNameRoute,
  AuthenticatedProgramKamiAdopsiPohonIndexRoute:
    AuthenticatedProgramKamiAdopsiPohonIndexRoute,
  AuthenticatedProgramKamiMonitorBiodiversityIndexRoute:
    AuthenticatedProgramKamiMonitorBiodiversityIndexRoute,
  AuthenticatedProgramKamiPatroliGeoTaggingIndexRoute:
    AuthenticatedProgramKamiPatroliGeoTaggingIndexRoute,
  AuthenticatedProgramKamiPemberdayaanMasyarakatIndexRoute:
    AuthenticatedProgramKamiPemberdayaanMasyarakatIndexRoute,
  AuthenticatedTentangKamiKelompokKomunitasIndexRoute:
    AuthenticatedTentangKamiKelompokKomunitasIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthenticatedadminRouteChildren {
  AuthenticatedadminAdminProfileRoute: typeof AuthenticatedadminAdminProfileRoute
  AuthenticatedadminAdminIndexRoute: typeof AuthenticatedadminAdminIndexRoute
  AuthenticatedadminAdminMasterPohonAddMasterTreeRoute: typeof AuthenticatedadminAdminMasterPohonAddMasterTreeRoute
  AuthenticatedadminAdminTentangKamiKelompokKomunitasAddKomunitasRoute: typeof AuthenticatedadminAdminTentangKamiKelompokKomunitasAddKomunitasRoute
  AuthenticatedadminAdminConfigRolePermissionIndexRoute: typeof AuthenticatedadminAdminConfigRolePermissionIndexRoute
  AuthenticatedadminAdminConfigUserIndexRoute: typeof AuthenticatedadminAdminConfigUserIndexRoute
  AuthenticatedadminAdminDataPohonIndexRoute: typeof AuthenticatedadminAdminDataPohonIndexRoute
  AuthenticatedadminAdminMasterPohonIndexRoute: typeof AuthenticatedadminAdminMasterPohonIndexRoute
  AuthenticatedadminAdminTentangKamiKelompokKomunitasIndexRoute: typeof AuthenticatedadminAdminTentangKamiKelompokKomunitasIndexRoute
  AuthenticatedadminAdminMasterPohonUpdateMasterTreeIdRoute: typeof AuthenticatedadminAdminMasterPohonUpdateMasterTreeIdRoute
  AuthenticatedadminAdminConfigUserAddIndexRoute: typeof AuthenticatedadminAdminConfigUserAddIndexRoute
  AuthenticatedadminAdminDataPohonTreeIdIndexRoute: typeof AuthenticatedadminAdminDataPohonTreeIdIndexRoute
  AuthenticatedadminAdminDataPohonAddIndexRoute: typeof AuthenticatedadminAdminDataPohonAddIndexRoute
  AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdIndexRoute: typeof AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdIndexRoute
  AuthenticatedadminAdminConfigUserUserIdUpdateIndexRoute: typeof AuthenticatedadminAdminConfigUserUserIdUpdateIndexRoute
  AuthenticatedadminAdminDataPohonTreeIdSurveyHistoryIndexRoute: typeof AuthenticatedadminAdminDataPohonTreeIdSurveyHistoryIndexRoute
  AuthenticatedadminAdminDataPohonTreeIdUpdateIndexRoute: typeof AuthenticatedadminAdminDataPohonTreeIdUpdateIndexRoute
  AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasIndexRoute: typeof AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasIndexRoute
  AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAllPhotosIndexRoute: typeof AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAllPhotosIndexRoute
  AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdUpdateKomunitasIndexRoute: typeof AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdUpdateKomunitasIndexRoute
  AuthenticatedadminAdminDataPohonTreeIdSurveyHistoryAddIndexRoute: typeof AuthenticatedadminAdminDataPohonTreeIdSurveyHistoryAddIndexRoute
  AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasAddIndexRoute: typeof AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasAddIndexRoute
  AuthenticatedadminAdminDataPohonTreeIdSurveyHistorySurveyHistoryIdUpdateIndexRoute: typeof AuthenticatedadminAdminDataPohonTreeIdSurveyHistorySurveyHistoryIdUpdateIndexRoute
  AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasGroupActivityIdUpdateIndexRoute: typeof AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasGroupActivityIdUpdateIndexRoute
}

const AuthenticatedadminRouteChildren: AuthenticatedadminRouteChildren = {
  AuthenticatedadminAdminProfileRoute: AuthenticatedadminAdminProfileRoute,
  AuthenticatedadminAdminIndexRoute: AuthenticatedadminAdminIndexRoute,
  AuthenticatedadminAdminMasterPohonAddMasterTreeRoute:
    AuthenticatedadminAdminMasterPohonAddMasterTreeRoute,
  AuthenticatedadminAdminTentangKamiKelompokKomunitasAddKomunitasRoute:
    AuthenticatedadminAdminTentangKamiKelompokKomunitasAddKomunitasRoute,
  AuthenticatedadminAdminConfigRolePermissionIndexRoute:
    AuthenticatedadminAdminConfigRolePermissionIndexRoute,
  AuthenticatedadminAdminConfigUserIndexRoute:
    AuthenticatedadminAdminConfigUserIndexRoute,
  AuthenticatedadminAdminDataPohonIndexRoute:
    AuthenticatedadminAdminDataPohonIndexRoute,
  AuthenticatedadminAdminMasterPohonIndexRoute:
    AuthenticatedadminAdminMasterPohonIndexRoute,
  AuthenticatedadminAdminTentangKamiKelompokKomunitasIndexRoute:
    AuthenticatedadminAdminTentangKamiKelompokKomunitasIndexRoute,
  AuthenticatedadminAdminMasterPohonUpdateMasterTreeIdRoute:
    AuthenticatedadminAdminMasterPohonUpdateMasterTreeIdRoute,
  AuthenticatedadminAdminConfigUserAddIndexRoute:
    AuthenticatedadminAdminConfigUserAddIndexRoute,
  AuthenticatedadminAdminDataPohonTreeIdIndexRoute:
    AuthenticatedadminAdminDataPohonTreeIdIndexRoute,
  AuthenticatedadminAdminDataPohonAddIndexRoute:
    AuthenticatedadminAdminDataPohonAddIndexRoute,
  AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdIndexRoute:
    AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdIndexRoute,
  AuthenticatedadminAdminConfigUserUserIdUpdateIndexRoute:
    AuthenticatedadminAdminConfigUserUserIdUpdateIndexRoute,
  AuthenticatedadminAdminDataPohonTreeIdSurveyHistoryIndexRoute:
    AuthenticatedadminAdminDataPohonTreeIdSurveyHistoryIndexRoute,
  AuthenticatedadminAdminDataPohonTreeIdUpdateIndexRoute:
    AuthenticatedadminAdminDataPohonTreeIdUpdateIndexRoute,
  AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasIndexRoute:
    AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasIndexRoute,
  AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAllPhotosIndexRoute:
    AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAllPhotosIndexRoute,
  AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdUpdateKomunitasIndexRoute:
    AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdUpdateKomunitasIndexRoute,
  AuthenticatedadminAdminDataPohonTreeIdSurveyHistoryAddIndexRoute:
    AuthenticatedadminAdminDataPohonTreeIdSurveyHistoryAddIndexRoute,
  AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasAddIndexRoute:
    AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasAddIndexRoute,
  AuthenticatedadminAdminDataPohonTreeIdSurveyHistorySurveyHistoryIdUpdateIndexRoute:
    AuthenticatedadminAdminDataPohonTreeIdSurveyHistorySurveyHistoryIdUpdateIndexRoute,
  AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasGroupActivityIdUpdateIndexRoute:
    AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasGroupActivityIdUpdateIndexRoute,
}

const AuthenticatedadminRouteWithChildren =
  AuthenticatedadminRoute._addFileChildren(AuthenticatedadminRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedadminRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/': typeof AuthenticatedIndexRoute
  '/tentang-kami': typeof TentangKamiIndexRoute
  '/admin/profile': typeof AuthenticatedadminAdminProfileRoute
  '/program-kami': typeof AuthenticatedProgramKamiIndexRoute
  '/admin': typeof AuthenticatedadminAdminIndexRoute
  '/tentang-kami/apa-itu-adopsi-pohon': typeof TentangKamiApaItuAdopsiPohonIndexRoute
  '/tentang-kami/kelompok-komunitas/$kelompokKomunitasName': typeof AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasNameRoute
  '/program-kami/adopsi-pohon': typeof AuthenticatedProgramKamiAdopsiPohonIndexRoute
  '/program-kami/monitor-biodiversity': typeof AuthenticatedProgramKamiMonitorBiodiversityIndexRoute
  '/program-kami/patroli-&-geo-tagging': typeof AuthenticatedProgramKamiPatroliGeoTaggingIndexRoute
  '/program-kami/pemberdayaan-masyarakat': typeof AuthenticatedProgramKamiPemberdayaanMasyarakatIndexRoute
  '/tentang-kami/kelompok-komunitas': typeof AuthenticatedTentangKamiKelompokKomunitasIndexRoute
  '/admin/master/pohon/add-master-tree': typeof AuthenticatedadminAdminMasterPohonAddMasterTreeRoute
  '/admin/tentang-kami/kelompok-komunitas/add-komunitas': typeof AuthenticatedadminAdminTentangKamiKelompokKomunitasAddKomunitasRoute
  '/admin/config/role-permission': typeof AuthenticatedadminAdminConfigRolePermissionIndexRoute
  '/admin/config/user': typeof AuthenticatedadminAdminConfigUserIndexRoute
  '/admin/data/pohon': typeof AuthenticatedadminAdminDataPohonIndexRoute
  '/admin/master/pohon': typeof AuthenticatedadminAdminMasterPohonIndexRoute
  '/admin/tentang-kami/kelompok-komunitas': typeof AuthenticatedadminAdminTentangKamiKelompokKomunitasIndexRoute
  '/admin/master/pohon/update/$masterTreeId': typeof AuthenticatedadminAdminMasterPohonUpdateMasterTreeIdRoute
  '/admin/config/user/add': typeof AuthenticatedadminAdminConfigUserAddIndexRoute
  '/admin/data/pohon/$treeId': typeof AuthenticatedadminAdminDataPohonTreeIdIndexRoute
  '/admin/data/pohon/add': typeof AuthenticatedadminAdminDataPohonAddIndexRoute
  '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId': typeof AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdIndexRoute
  '/admin/config/user/$userId/update': typeof AuthenticatedadminAdminConfigUserUserIdUpdateIndexRoute
  '/admin/data/pohon/$treeId/survey-history': typeof AuthenticatedadminAdminDataPohonTreeIdSurveyHistoryIndexRoute
  '/admin/data/pohon/$treeId/update': typeof AuthenticatedadminAdminDataPohonTreeIdUpdateIndexRoute
  '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas': typeof AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasIndexRoute
  '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/all-photos': typeof AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAllPhotosIndexRoute
  '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/update-komunitas': typeof AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdUpdateKomunitasIndexRoute
  '/admin/data/pohon/$treeId/survey-history/add': typeof AuthenticatedadminAdminDataPohonTreeIdSurveyHistoryAddIndexRoute
  '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/add': typeof AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasAddIndexRoute
  '/admin/data/pohon/$treeId/survey-history/$surveyHistoryId/update': typeof AuthenticatedadminAdminDataPohonTreeIdSurveyHistorySurveyHistoryIdUpdateIndexRoute
  '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/$groupActivityId/update': typeof AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasGroupActivityIdUpdateIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AuthenticatedadminRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/': typeof AuthenticatedIndexRoute
  '/tentang-kami': typeof TentangKamiIndexRoute
  '/admin/profile': typeof AuthenticatedadminAdminProfileRoute
  '/program-kami': typeof AuthenticatedProgramKamiIndexRoute
  '/admin': typeof AuthenticatedadminAdminIndexRoute
  '/tentang-kami/apa-itu-adopsi-pohon': typeof TentangKamiApaItuAdopsiPohonIndexRoute
  '/tentang-kami/kelompok-komunitas/$kelompokKomunitasName': typeof AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasNameRoute
  '/program-kami/adopsi-pohon': typeof AuthenticatedProgramKamiAdopsiPohonIndexRoute
  '/program-kami/monitor-biodiversity': typeof AuthenticatedProgramKamiMonitorBiodiversityIndexRoute
  '/program-kami/patroli-&-geo-tagging': typeof AuthenticatedProgramKamiPatroliGeoTaggingIndexRoute
  '/program-kami/pemberdayaan-masyarakat': typeof AuthenticatedProgramKamiPemberdayaanMasyarakatIndexRoute
  '/tentang-kami/kelompok-komunitas': typeof AuthenticatedTentangKamiKelompokKomunitasIndexRoute
  '/admin/master/pohon/add-master-tree': typeof AuthenticatedadminAdminMasterPohonAddMasterTreeRoute
  '/admin/tentang-kami/kelompok-komunitas/add-komunitas': typeof AuthenticatedadminAdminTentangKamiKelompokKomunitasAddKomunitasRoute
  '/admin/config/role-permission': typeof AuthenticatedadminAdminConfigRolePermissionIndexRoute
  '/admin/config/user': typeof AuthenticatedadminAdminConfigUserIndexRoute
  '/admin/data/pohon': typeof AuthenticatedadminAdminDataPohonIndexRoute
  '/admin/master/pohon': typeof AuthenticatedadminAdminMasterPohonIndexRoute
  '/admin/tentang-kami/kelompok-komunitas': typeof AuthenticatedadminAdminTentangKamiKelompokKomunitasIndexRoute
  '/admin/master/pohon/update/$masterTreeId': typeof AuthenticatedadminAdminMasterPohonUpdateMasterTreeIdRoute
  '/admin/config/user/add': typeof AuthenticatedadminAdminConfigUserAddIndexRoute
  '/admin/data/pohon/$treeId': typeof AuthenticatedadminAdminDataPohonTreeIdIndexRoute
  '/admin/data/pohon/add': typeof AuthenticatedadminAdminDataPohonAddIndexRoute
  '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId': typeof AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdIndexRoute
  '/admin/config/user/$userId/update': typeof AuthenticatedadminAdminConfigUserUserIdUpdateIndexRoute
  '/admin/data/pohon/$treeId/survey-history': typeof AuthenticatedadminAdminDataPohonTreeIdSurveyHistoryIndexRoute
  '/admin/data/pohon/$treeId/update': typeof AuthenticatedadminAdminDataPohonTreeIdUpdateIndexRoute
  '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas': typeof AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasIndexRoute
  '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/all-photos': typeof AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAllPhotosIndexRoute
  '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/update-komunitas': typeof AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdUpdateKomunitasIndexRoute
  '/admin/data/pohon/$treeId/survey-history/add': typeof AuthenticatedadminAdminDataPohonTreeIdSurveyHistoryAddIndexRoute
  '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/add': typeof AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasAddIndexRoute
  '/admin/data/pohon/$treeId/survey-history/$surveyHistoryId/update': typeof AuthenticatedadminAdminDataPohonTreeIdSurveyHistorySurveyHistoryIdUpdateIndexRoute
  '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/$groupActivityId/update': typeof AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasGroupActivityIdUpdateIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated_admin': typeof AuthenticatedadminRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/tentang-kami/': typeof TentangKamiIndexRoute
  '/_authenticated_admin/admin/profile': typeof AuthenticatedadminAdminProfileRoute
  '/_authenticated/program-kami/': typeof AuthenticatedProgramKamiIndexRoute
  '/_authenticated_admin/admin/': typeof AuthenticatedadminAdminIndexRoute
  '/tentang-kami/apa-itu-adopsi-pohon/': typeof TentangKamiApaItuAdopsiPohonIndexRoute
  '/_authenticated/tentang-kami/kelompok-komunitas/$kelompokKomunitasName': typeof AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasNameRoute
  '/_authenticated/program-kami/adopsi-pohon/': typeof AuthenticatedProgramKamiAdopsiPohonIndexRoute
  '/_authenticated/program-kami/monitor-biodiversity/': typeof AuthenticatedProgramKamiMonitorBiodiversityIndexRoute
  '/_authenticated/program-kami/patroli-&-geo-tagging/': typeof AuthenticatedProgramKamiPatroliGeoTaggingIndexRoute
  '/_authenticated/program-kami/pemberdayaan-masyarakat/': typeof AuthenticatedProgramKamiPemberdayaanMasyarakatIndexRoute
  '/_authenticated/tentang-kami/kelompok-komunitas/': typeof AuthenticatedTentangKamiKelompokKomunitasIndexRoute
  '/_authenticated_admin/admin/master/pohon/add-master-tree': typeof AuthenticatedadminAdminMasterPohonAddMasterTreeRoute
  '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/add-komunitas': typeof AuthenticatedadminAdminTentangKamiKelompokKomunitasAddKomunitasRoute
  '/_authenticated_admin/admin/config/role-permission/': typeof AuthenticatedadminAdminConfigRolePermissionIndexRoute
  '/_authenticated_admin/admin/config/user/': typeof AuthenticatedadminAdminConfigUserIndexRoute
  '/_authenticated_admin/admin/data/pohon/': typeof AuthenticatedadminAdminDataPohonIndexRoute
  '/_authenticated_admin/admin/master/pohon/': typeof AuthenticatedadminAdminMasterPohonIndexRoute
  '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/': typeof AuthenticatedadminAdminTentangKamiKelompokKomunitasIndexRoute
  '/_authenticated_admin/admin/master/pohon/update/$masterTreeId': typeof AuthenticatedadminAdminMasterPohonUpdateMasterTreeIdRoute
  '/_authenticated_admin/admin/config/user/add/': typeof AuthenticatedadminAdminConfigUserAddIndexRoute
  '/_authenticated_admin/admin/data/pohon/$treeId/': typeof AuthenticatedadminAdminDataPohonTreeIdIndexRoute
  '/_authenticated_admin/admin/data/pohon/add/': typeof AuthenticatedadminAdminDataPohonAddIndexRoute
  '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/': typeof AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdIndexRoute
  '/_authenticated_admin/admin/config/user/$userId/update/': typeof AuthenticatedadminAdminConfigUserUserIdUpdateIndexRoute
  '/_authenticated_admin/admin/data/pohon/$treeId/survey-history/': typeof AuthenticatedadminAdminDataPohonTreeIdSurveyHistoryIndexRoute
  '/_authenticated_admin/admin/data/pohon/$treeId/update/': typeof AuthenticatedadminAdminDataPohonTreeIdUpdateIndexRoute
  '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/': typeof AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasIndexRoute
  '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/all-photos/': typeof AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAllPhotosIndexRoute
  '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/update-komunitas/': typeof AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdUpdateKomunitasIndexRoute
  '/_authenticated_admin/admin/data/pohon/$treeId/survey-history/add/': typeof AuthenticatedadminAdminDataPohonTreeIdSurveyHistoryAddIndexRoute
  '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/add/': typeof AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasAddIndexRoute
  '/_authenticated_admin/admin/data/pohon/$treeId/survey-history/$surveyHistoryId/update/': typeof AuthenticatedadminAdminDataPohonTreeIdSurveyHistorySurveyHistoryIdUpdateIndexRoute
  '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/$groupActivityId/update/': typeof AuthenticatedadminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasGroupActivityIdUpdateIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/about'
    | '/login'
    | '/register'
    | '/profile'
    | '/'
    | '/tentang-kami'
    | '/admin/profile'
    | '/program-kami'
    | '/admin'
    | '/tentang-kami/apa-itu-adopsi-pohon'
    | '/tentang-kami/kelompok-komunitas/$kelompokKomunitasName'
    | '/program-kami/adopsi-pohon'
    | '/program-kami/monitor-biodiversity'
    | '/program-kami/patroli-&-geo-tagging'
    | '/program-kami/pemberdayaan-masyarakat'
    | '/tentang-kami/kelompok-komunitas'
    | '/admin/master/pohon/add-master-tree'
    | '/admin/tentang-kami/kelompok-komunitas/add-komunitas'
    | '/admin/config/role-permission'
    | '/admin/config/user'
    | '/admin/data/pohon'
    | '/admin/master/pohon'
    | '/admin/tentang-kami/kelompok-komunitas'
    | '/admin/master/pohon/update/$masterTreeId'
    | '/admin/config/user/add'
    | '/admin/data/pohon/$treeId'
    | '/admin/data/pohon/add'
    | '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId'
    | '/admin/config/user/$userId/update'
    | '/admin/data/pohon/$treeId/survey-history'
    | '/admin/data/pohon/$treeId/update'
    | '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas'
    | '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/all-photos'
    | '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/update-komunitas'
    | '/admin/data/pohon/$treeId/survey-history/add'
    | '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/add'
    | '/admin/data/pohon/$treeId/survey-history/$surveyHistoryId/update'
    | '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/$groupActivityId/update'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/about'
    | '/login'
    | '/register'
    | '/profile'
    | '/'
    | '/tentang-kami'
    | '/admin/profile'
    | '/program-kami'
    | '/admin'
    | '/tentang-kami/apa-itu-adopsi-pohon'
    | '/tentang-kami/kelompok-komunitas/$kelompokKomunitasName'
    | '/program-kami/adopsi-pohon'
    | '/program-kami/monitor-biodiversity'
    | '/program-kami/patroli-&-geo-tagging'
    | '/program-kami/pemberdayaan-masyarakat'
    | '/tentang-kami/kelompok-komunitas'
    | '/admin/master/pohon/add-master-tree'
    | '/admin/tentang-kami/kelompok-komunitas/add-komunitas'
    | '/admin/config/role-permission'
    | '/admin/config/user'
    | '/admin/data/pohon'
    | '/admin/master/pohon'
    | '/admin/tentang-kami/kelompok-komunitas'
    | '/admin/master/pohon/update/$masterTreeId'
    | '/admin/config/user/add'
    | '/admin/data/pohon/$treeId'
    | '/admin/data/pohon/add'
    | '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId'
    | '/admin/config/user/$userId/update'
    | '/admin/data/pohon/$treeId/survey-history'
    | '/admin/data/pohon/$treeId/update'
    | '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas'
    | '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/all-photos'
    | '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/update-komunitas'
    | '/admin/data/pohon/$treeId/survey-history/add'
    | '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/add'
    | '/admin/data/pohon/$treeId/survey-history/$surveyHistoryId/update'
    | '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/$groupActivityId/update'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated_admin'
    | '/about'
    | '/login'
    | '/register'
    | '/_authenticated/profile'
    | '/_authenticated/'
    | '/tentang-kami/'
    | '/_authenticated_admin/admin/profile'
    | '/_authenticated/program-kami/'
    | '/_authenticated_admin/admin/'
    | '/tentang-kami/apa-itu-adopsi-pohon/'
    | '/_authenticated/tentang-kami/kelompok-komunitas/$kelompokKomunitasName'
    | '/_authenticated/program-kami/adopsi-pohon/'
    | '/_authenticated/program-kami/monitor-biodiversity/'
    | '/_authenticated/program-kami/patroli-&-geo-tagging/'
    | '/_authenticated/program-kami/pemberdayaan-masyarakat/'
    | '/_authenticated/tentang-kami/kelompok-komunitas/'
    | '/_authenticated_admin/admin/master/pohon/add-master-tree'
    | '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/add-komunitas'
    | '/_authenticated_admin/admin/config/role-permission/'
    | '/_authenticated_admin/admin/config/user/'
    | '/_authenticated_admin/admin/data/pohon/'
    | '/_authenticated_admin/admin/master/pohon/'
    | '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/'
    | '/_authenticated_admin/admin/master/pohon/update/$masterTreeId'
    | '/_authenticated_admin/admin/config/user/add/'
    | '/_authenticated_admin/admin/data/pohon/$treeId/'
    | '/_authenticated_admin/admin/data/pohon/add/'
    | '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/'
    | '/_authenticated_admin/admin/config/user/$userId/update/'
    | '/_authenticated_admin/admin/data/pohon/$treeId/survey-history/'
    | '/_authenticated_admin/admin/data/pohon/$treeId/update/'
    | '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/'
    | '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/all-photos/'
    | '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/update-komunitas/'
    | '/_authenticated_admin/admin/data/pohon/$treeId/survey-history/add/'
    | '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/add/'
    | '/_authenticated_admin/admin/data/pohon/$treeId/survey-history/$surveyHistoryId/update/'
    | '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/$groupActivityId/update/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthenticatedadminRoute: typeof AuthenticatedadminRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  TentangKamiIndexRoute: typeof TentangKamiIndexRoute
  TentangKamiApaItuAdopsiPohonIndexRoute: typeof TentangKamiApaItuAdopsiPohonIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthenticatedadminRoute: AuthenticatedadminRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  TentangKamiIndexRoute: TentangKamiIndexRoute,
  TentangKamiApaItuAdopsiPohonIndexRoute:
    TentangKamiApaItuAdopsiPohonIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/_authenticated_admin",
        "/about",
        "/login",
        "/register",
        "/tentang-kami/",
        "/tentang-kami/apa-itu-adopsi-pohon/"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/profile",
        "/_authenticated/",
        "/_authenticated/program-kami/",
        "/_authenticated/tentang-kami/kelompok-komunitas/$kelompokKomunitasName",
        "/_authenticated/program-kami/adopsi-pohon/",
        "/_authenticated/program-kami/monitor-biodiversity/",
        "/_authenticated/program-kami/patroli-&-geo-tagging/",
        "/_authenticated/program-kami/pemberdayaan-masyarakat/",
        "/_authenticated/tentang-kami/kelompok-komunitas/"
      ]
    },
    "/_authenticated_admin": {
      "filePath": "_authenticated_admin.tsx",
      "children": [
        "/_authenticated_admin/admin/profile",
        "/_authenticated_admin/admin/",
        "/_authenticated_admin/admin/master/pohon/add-master-tree",
        "/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/add-komunitas",
        "/_authenticated_admin/admin/config/role-permission/",
        "/_authenticated_admin/admin/config/user/",
        "/_authenticated_admin/admin/data/pohon/",
        "/_authenticated_admin/admin/master/pohon/",
        "/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/",
        "/_authenticated_admin/admin/master/pohon/update/$masterTreeId",
        "/_authenticated_admin/admin/config/user/add/",
        "/_authenticated_admin/admin/data/pohon/$treeId/",
        "/_authenticated_admin/admin/data/pohon/add/",
        "/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/",
        "/_authenticated_admin/admin/config/user/$userId/update/",
        "/_authenticated_admin/admin/data/pohon/$treeId/survey-history/",
        "/_authenticated_admin/admin/data/pohon/$treeId/update/",
        "/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/",
        "/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/all-photos/",
        "/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/update-komunitas/",
        "/_authenticated_admin/admin/data/pohon/$treeId/survey-history/add/",
        "/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/add/",
        "/_authenticated_admin/admin/data/pohon/$treeId/survey-history/$surveyHistoryId/update/",
        "/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/$groupActivityId/update/"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/_authenticated/profile": {
      "filePath": "_authenticated/profile.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/tentang-kami/": {
      "filePath": "tentang-kami/index.tsx"
    },
    "/_authenticated_admin/admin/profile": {
      "filePath": "_authenticated_admin/admin/profile.tsx",
      "parent": "/_authenticated_admin"
    },
    "/_authenticated/program-kami/": {
      "filePath": "_authenticated/program-kami/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated_admin/admin/": {
      "filePath": "_authenticated_admin/admin/index.tsx",
      "parent": "/_authenticated_admin"
    },
    "/tentang-kami/apa-itu-adopsi-pohon/": {
      "filePath": "tentang-kami/apa-itu-adopsi-pohon/index.tsx"
    },
    "/_authenticated/tentang-kami/kelompok-komunitas/$kelompokKomunitasName": {
      "filePath": "_authenticated/tentang-kami/kelompok-komunitas/$kelompokKomunitasName.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/program-kami/adopsi-pohon/": {
      "filePath": "_authenticated/program-kami/adopsi-pohon/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/program-kami/monitor-biodiversity/": {
      "filePath": "_authenticated/program-kami/monitor-biodiversity/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/program-kami/patroli-&-geo-tagging/": {
      "filePath": "_authenticated/program-kami/patroli-&-geo-tagging/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/program-kami/pemberdayaan-masyarakat/": {
      "filePath": "_authenticated/program-kami/pemberdayaan-masyarakat/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/tentang-kami/kelompok-komunitas/": {
      "filePath": "_authenticated/tentang-kami/kelompok-komunitas/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated_admin/admin/master/pohon/add-master-tree": {
      "filePath": "_authenticated_admin/admin/master/pohon/add-master-tree.tsx",
      "parent": "/_authenticated_admin"
    },
    "/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/add-komunitas": {
      "filePath": "_authenticated_admin/admin/tentang-kami/kelompok-komunitas/add-komunitas.tsx",
      "parent": "/_authenticated_admin"
    },
    "/_authenticated_admin/admin/config/role-permission/": {
      "filePath": "_authenticated_admin/admin/config/role-permission/index.tsx",
      "parent": "/_authenticated_admin"
    },
    "/_authenticated_admin/admin/config/user/": {
      "filePath": "_authenticated_admin/admin/config/user/index.tsx",
      "parent": "/_authenticated_admin"
    },
    "/_authenticated_admin/admin/data/pohon/": {
      "filePath": "_authenticated_admin/admin/data/pohon/index.tsx",
      "parent": "/_authenticated_admin"
    },
    "/_authenticated_admin/admin/master/pohon/": {
      "filePath": "_authenticated_admin/admin/master/pohon/index.tsx",
      "parent": "/_authenticated_admin"
    },
    "/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/": {
      "filePath": "_authenticated_admin/admin/tentang-kami/kelompok-komunitas/index.tsx",
      "parent": "/_authenticated_admin"
    },
    "/_authenticated_admin/admin/master/pohon/update/$masterTreeId": {
      "filePath": "_authenticated_admin/admin/master/pohon/update/$masterTreeId.tsx",
      "parent": "/_authenticated_admin"
    },
    "/_authenticated_admin/admin/config/user/add/": {
      "filePath": "_authenticated_admin/admin/config/user/add/index.tsx",
      "parent": "/_authenticated_admin"
    },
    "/_authenticated_admin/admin/data/pohon/$treeId/": {
      "filePath": "_authenticated_admin/admin/data/pohon/$treeId/index.tsx",
      "parent": "/_authenticated_admin"
    },
    "/_authenticated_admin/admin/data/pohon/add/": {
      "filePath": "_authenticated_admin/admin/data/pohon/add/index.tsx",
      "parent": "/_authenticated_admin"
    },
    "/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/": {
      "filePath": "_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/index.tsx",
      "parent": "/_authenticated_admin"
    },
    "/_authenticated_admin/admin/config/user/$userId/update/": {
      "filePath": "_authenticated_admin/admin/config/user/$userId/update/index.tsx",
      "parent": "/_authenticated_admin"
    },
    "/_authenticated_admin/admin/data/pohon/$treeId/survey-history/": {
      "filePath": "_authenticated_admin/admin/data/pohon/$treeId/survey-history/index.tsx",
      "parent": "/_authenticated_admin"
    },
    "/_authenticated_admin/admin/data/pohon/$treeId/update/": {
      "filePath": "_authenticated_admin/admin/data/pohon/$treeId/update/index.tsx",
      "parent": "/_authenticated_admin"
    },
    "/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/": {
      "filePath": "_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/index.tsx",
      "parent": "/_authenticated_admin"
    },
    "/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/all-photos/": {
      "filePath": "_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/all-photos/index.tsx",
      "parent": "/_authenticated_admin"
    },
    "/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/update-komunitas/": {
      "filePath": "_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/update-komunitas/index.tsx",
      "parent": "/_authenticated_admin"
    },
    "/_authenticated_admin/admin/data/pohon/$treeId/survey-history/add/": {
      "filePath": "_authenticated_admin/admin/data/pohon/$treeId/survey-history/add/index.tsx",
      "parent": "/_authenticated_admin"
    },
    "/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/add/": {
      "filePath": "_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/add/index.tsx",
      "parent": "/_authenticated_admin"
    },
    "/_authenticated_admin/admin/data/pohon/$treeId/survey-history/$surveyHistoryId/update/": {
      "filePath": "_authenticated_admin/admin/data/pohon/$treeId/survey-history/$surveyHistoryId/update/index.tsx",
      "parent": "/_authenticated_admin"
    },
    "/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/$groupActivityId/update/": {
      "filePath": "_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/$groupActivityId/update/index.tsx",
      "parent": "/_authenticated_admin"
    }
  }
}
ROUTE_MANIFEST_END */
