/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as Authenticated_adminRouteImport } from './routes/_authenticated_admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as TentangKamiIndexRouteImport } from './routes/tentang-kami/index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as TentangKamiApaItuAdopsiPohonIndexRouteImport } from './routes/tentang-kami/apa-itu-adopsi-pohon/index'
import { Route as Authenticated_adminAdminIndexRouteImport } from './routes/_authenticated_admin/admin/index'
import { Route as AuthenticatedProgramKamiIndexRouteImport } from './routes/_authenticated/program-kami/index'
import { Route as AuthenticatedPemetaanIndexRouteImport } from './routes/_authenticated/pemetaan/index'
import { Route as Authenticated_adminAdminProfileRouteImport } from './routes/_authenticated_admin/admin/profile'
import { Route as Authenticated_adminAdminPemetaanIndexRouteImport } from './routes/_authenticated_admin/admin/pemetaan/index'
import { Route as AuthenticatedTentangKamiKelompokKomunitasIndexRouteImport } from './routes/_authenticated/tentang-kami/kelompok-komunitas/index'
import { Route as AuthenticatedProgramKamiPemberdayaanMasyarakatIndexRouteImport } from './routes/_authenticated/program-kami/pemberdayaan-masyarakat/index'
import { Route as AuthenticatedProgramKamiPatroliChar38GeoTaggingIndexRouteImport } from './routes/_authenticated/program-kami/patroli-&-geo-tagging/index'
import { Route as AuthenticatedProgramKamiMonitorBiodiversityIndexRouteImport } from './routes/_authenticated/program-kami/monitor-biodiversity/index'
import { Route as AuthenticatedProgramKamiAdopsiPohonIndexRouteImport } from './routes/_authenticated/program-kami/adopsi-pohon/index'
import { Route as AuthenticatedDataPohonIndexRouteImport } from './routes/_authenticated/data/pohon/index'
import { Route as AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasNameRouteImport } from './routes/_authenticated/tentang-kami/kelompok-komunitas/$kelompokKomunitasName'
import { Route as Authenticated_adminAdminTentangKamiKelompokKomunitasIndexRouteImport } from './routes/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/index'
import { Route as Authenticated_adminAdminMasterPohonIndexRouteImport } from './routes/_authenticated_admin/admin/master/pohon/index'
import { Route as Authenticated_adminAdminMasterPohonLokalIndexRouteImport } from './routes/_authenticated_admin/admin/master/pohon-lokal/index'
import { Route as Authenticated_adminAdminMasterKodePatokBatasIndexRouteImport } from './routes/_authenticated_admin/admin/master/kode-patok-batas/index'
import { Route as Authenticated_adminAdminDataPohonIndexRouteImport } from './routes/_authenticated_admin/admin/data/pohon/index'
import { Route as Authenticated_adminAdminDataPatokBatasIndexRouteImport } from './routes/_authenticated_admin/admin/data/patok-batas/index'
import { Route as Authenticated_adminAdminConfigUserIndexRouteImport } from './routes/_authenticated_admin/admin/config/user/index'
import { Route as Authenticated_adminAdminConfigRolePermissionIndexRouteImport } from './routes/_authenticated_admin/admin/config/role-permission/index'
import { Route as AuthenticatedDataPohonTreeIdIndexRouteImport } from './routes/_authenticated/data/pohon/$treeId/index'
import { Route as Authenticated_adminAdminTentangKamiKelompokKomunitasAddKomunitasRouteImport } from './routes/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/add-komunitas'
import { Route as Authenticated_adminAdminMasterPohonAddMasterTreeRouteImport } from './routes/_authenticated_admin/admin/master/pohon/add-master-tree'
import { Route as Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdIndexRouteImport } from './routes/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/index'
import { Route as Authenticated_adminAdminMasterPohonLokalAddIndexRouteImport } from './routes/_authenticated_admin/admin/master/pohon-lokal/add/index'
import { Route as Authenticated_adminAdminMasterKodePatokBatasAddIndexRouteImport } from './routes/_authenticated_admin/admin/master/kode-patok-batas/add/index'
import { Route as Authenticated_adminAdminDataPohonAddIndexRouteImport } from './routes/_authenticated_admin/admin/data/pohon/add/index'
import { Route as Authenticated_adminAdminDataPohonTreeIdIndexRouteImport } from './routes/_authenticated_admin/admin/data/pohon/$treeId/index'
import { Route as Authenticated_adminAdminDataPatokBatasAddIndexRouteImport } from './routes/_authenticated_admin/admin/data/patok-batas/add/index'
import { Route as Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdIndexRouteImport } from './routes/_authenticated_admin/admin/data/patok-batas/$boundaryMarkerId/index'
import { Route as Authenticated_adminAdminConfigUserAddIndexRouteImport } from './routes/_authenticated_admin/admin/config/user/add/index'
import { Route as Authenticated_adminAdminMasterPohonUpdateMasterTreeIdRouteImport } from './routes/_authenticated_admin/admin/master/pohon/update/$masterTreeId'
import { Route as Authenticated_adminAdminMasterPohonLokalUpdateMasterLocalTreeIdRouteImport } from './routes/_authenticated_admin/admin/master/pohon-lokal/update/$masterLocalTreeId'
import { Route as Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdUpdateKomunitasIndexRouteImport } from './routes/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/update-komunitas/index'
import { Route as Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAllPhotosIndexRouteImport } from './routes/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/all-photos/index'
import { Route as Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasIndexRouteImport } from './routes/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/index'
import { Route as Authenticated_adminAdminMasterKodePatokBatasBoundaryMarkerCodeIdUpdateIndexRouteImport } from './routes/_authenticated_admin/admin/master/kode-patok-batas/$boundaryMarkerCodeId/update/index'
import { Route as Authenticated_adminAdminDataPohonTreeIdUpdateIndexRouteImport } from './routes/_authenticated_admin/admin/data/pohon/$treeId/update/index'
import { Route as Authenticated_adminAdminDataPohonTreeIdSurveyHistoryIndexRouteImport } from './routes/_authenticated_admin/admin/data/pohon/$treeId/survey-history/index'
import { Route as Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdUpdateIndexRouteImport } from './routes/_authenticated_admin/admin/data/patok-batas/$boundaryMarkerId/update/index'
import { Route as Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdCheckHistoryIndexRouteImport } from './routes/_authenticated_admin/admin/data/patok-batas/$boundaryMarkerId/check-history/index'
import { Route as Authenticated_adminAdminConfigUserUserIdUpdateIndexRouteImport } from './routes/_authenticated_admin/admin/config/user/$userId/update/index'
import { Route as Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasAddIndexRouteImport } from './routes/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/add/index'
import { Route as Authenticated_adminAdminDataPohonTreeIdSurveyHistoryAddIndexRouteImport } from './routes/_authenticated_admin/admin/data/pohon/$treeId/survey-history/add/index'
import { Route as Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdCheckHistoryAddIndexRouteImport } from './routes/_authenticated_admin/admin/data/patok-batas/$boundaryMarkerId/check-history/add/index'
import { Route as Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasGroupActivityIdUpdateIndexRouteImport } from './routes/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/$groupActivityId/update/index'
import { Route as Authenticated_adminAdminDataPohonTreeIdSurveyHistorySurveyHistoryIdUpdateIndexRouteImport } from './routes/_authenticated_admin/admin/data/pohon/$treeId/survey-history/$surveyHistoryId/update/index'
import { Route as Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdCheckHistoryCheckBmHistoryIdUpdateIndexRouteImport } from './routes/_authenticated_admin/admin/data/patok-batas/$boundaryMarkerId/check-history/$checkBmHistoryId/update/index'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const Authenticated_adminRoute = Authenticated_adminRouteImport.update({
  id: '/_authenticated_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangKamiIndexRoute = TentangKamiIndexRouteImport.update({
  id: '/tentang-kami/',
  path: '/tentang-kami/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const TentangKamiApaItuAdopsiPohonIndexRoute =
  TentangKamiApaItuAdopsiPohonIndexRouteImport.update({
    id: '/tentang-kami/apa-itu-adopsi-pohon/',
    path: '/tentang-kami/apa-itu-adopsi-pohon/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Authenticated_adminAdminIndexRoute =
  Authenticated_adminAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => Authenticated_adminRoute,
  } as any)
const AuthenticatedProgramKamiIndexRoute =
  AuthenticatedProgramKamiIndexRouteImport.update({
    id: '/program-kami/',
    path: '/program-kami/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPemetaanIndexRoute =
  AuthenticatedPemetaanIndexRouteImport.update({
    id: '/pemetaan/',
    path: '/pemetaan/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const Authenticated_adminAdminProfileRoute =
  Authenticated_adminAdminProfileRouteImport.update({
    id: '/admin/profile',
    path: '/admin/profile',
    getParentRoute: () => Authenticated_adminRoute,
  } as any)
const Authenticated_adminAdminPemetaanIndexRoute =
  Authenticated_adminAdminPemetaanIndexRouteImport.update({
    id: '/admin/pemetaan/',
    path: '/admin/pemetaan/',
    getParentRoute: () => Authenticated_adminRoute,
  } as any)
const AuthenticatedTentangKamiKelompokKomunitasIndexRoute =
  AuthenticatedTentangKamiKelompokKomunitasIndexRouteImport.update({
    id: '/tentang-kami/kelompok-komunitas/',
    path: '/tentang-kami/kelompok-komunitas/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProgramKamiPemberdayaanMasyarakatIndexRoute =
  AuthenticatedProgramKamiPemberdayaanMasyarakatIndexRouteImport.update({
    id: '/program-kami/pemberdayaan-masyarakat/',
    path: '/program-kami/pemberdayaan-masyarakat/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProgramKamiPatroliChar38GeoTaggingIndexRoute =
  AuthenticatedProgramKamiPatroliChar38GeoTaggingIndexRouteImport.update({
    id: '/program-kami/patroli-&-geo-tagging/',
    path: '/program-kami/patroli-&-geo-tagging/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProgramKamiMonitorBiodiversityIndexRoute =
  AuthenticatedProgramKamiMonitorBiodiversityIndexRouteImport.update({
    id: '/program-kami/monitor-biodiversity/',
    path: '/program-kami/monitor-biodiversity/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProgramKamiAdopsiPohonIndexRoute =
  AuthenticatedProgramKamiAdopsiPohonIndexRouteImport.update({
    id: '/program-kami/adopsi-pohon/',
    path: '/program-kami/adopsi-pohon/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDataPohonIndexRoute =
  AuthenticatedDataPohonIndexRouteImport.update({
    id: '/data/pohon/',
    path: '/data/pohon/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasNameRoute =
  AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasNameRouteImport.update(
    {
      id: '/tentang-kami/kelompok-komunitas/$kelompokKomunitasName',
      path: '/tentang-kami/kelompok-komunitas/$kelompokKomunitasName',
      getParentRoute: () => AuthenticatedRoute,
    } as any,
  )
const Authenticated_adminAdminTentangKamiKelompokKomunitasIndexRoute =
  Authenticated_adminAdminTentangKamiKelompokKomunitasIndexRouteImport.update({
    id: '/admin/tentang-kami/kelompok-komunitas/',
    path: '/admin/tentang-kami/kelompok-komunitas/',
    getParentRoute: () => Authenticated_adminRoute,
  } as any)
const Authenticated_adminAdminMasterPohonIndexRoute =
  Authenticated_adminAdminMasterPohonIndexRouteImport.update({
    id: '/admin/master/pohon/',
    path: '/admin/master/pohon/',
    getParentRoute: () => Authenticated_adminRoute,
  } as any)
const Authenticated_adminAdminMasterPohonLokalIndexRoute =
  Authenticated_adminAdminMasterPohonLokalIndexRouteImport.update({
    id: '/admin/master/pohon-lokal/',
    path: '/admin/master/pohon-lokal/',
    getParentRoute: () => Authenticated_adminRoute,
  } as any)
const Authenticated_adminAdminMasterKodePatokBatasIndexRoute =
  Authenticated_adminAdminMasterKodePatokBatasIndexRouteImport.update({
    id: '/admin/master/kode-patok-batas/',
    path: '/admin/master/kode-patok-batas/',
    getParentRoute: () => Authenticated_adminRoute,
  } as any)
const Authenticated_adminAdminDataPohonIndexRoute =
  Authenticated_adminAdminDataPohonIndexRouteImport.update({
    id: '/admin/data/pohon/',
    path: '/admin/data/pohon/',
    getParentRoute: () => Authenticated_adminRoute,
  } as any)
const Authenticated_adminAdminDataPatokBatasIndexRoute =
  Authenticated_adminAdminDataPatokBatasIndexRouteImport.update({
    id: '/admin/data/patok-batas/',
    path: '/admin/data/patok-batas/',
    getParentRoute: () => Authenticated_adminRoute,
  } as any)
const Authenticated_adminAdminConfigUserIndexRoute =
  Authenticated_adminAdminConfigUserIndexRouteImport.update({
    id: '/admin/config/user/',
    path: '/admin/config/user/',
    getParentRoute: () => Authenticated_adminRoute,
  } as any)
const Authenticated_adminAdminConfigRolePermissionIndexRoute =
  Authenticated_adminAdminConfigRolePermissionIndexRouteImport.update({
    id: '/admin/config/role-permission/',
    path: '/admin/config/role-permission/',
    getParentRoute: () => Authenticated_adminRoute,
  } as any)
const AuthenticatedDataPohonTreeIdIndexRoute =
  AuthenticatedDataPohonTreeIdIndexRouteImport.update({
    id: '/data/pohon/$treeId/',
    path: '/data/pohon/$treeId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const Authenticated_adminAdminTentangKamiKelompokKomunitasAddKomunitasRoute =
  Authenticated_adminAdminTentangKamiKelompokKomunitasAddKomunitasRouteImport.update(
    {
      id: '/admin/tentang-kami/kelompok-komunitas/add-komunitas',
      path: '/admin/tentang-kami/kelompok-komunitas/add-komunitas',
      getParentRoute: () => Authenticated_adminRoute,
    } as any,
  )
const Authenticated_adminAdminMasterPohonAddMasterTreeRoute =
  Authenticated_adminAdminMasterPohonAddMasterTreeRouteImport.update({
    id: '/admin/master/pohon/add-master-tree',
    path: '/admin/master/pohon/add-master-tree',
    getParentRoute: () => Authenticated_adminRoute,
  } as any)
const Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdIndexRoute =
  Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdIndexRouteImport.update(
    {
      id: '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/',
      path: '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/',
      getParentRoute: () => Authenticated_adminRoute,
    } as any,
  )
const Authenticated_adminAdminMasterPohonLokalAddIndexRoute =
  Authenticated_adminAdminMasterPohonLokalAddIndexRouteImport.update({
    id: '/admin/master/pohon-lokal/add/',
    path: '/admin/master/pohon-lokal/add/',
    getParentRoute: () => Authenticated_adminRoute,
  } as any)
const Authenticated_adminAdminMasterKodePatokBatasAddIndexRoute =
  Authenticated_adminAdminMasterKodePatokBatasAddIndexRouteImport.update({
    id: '/admin/master/kode-patok-batas/add/',
    path: '/admin/master/kode-patok-batas/add/',
    getParentRoute: () => Authenticated_adminRoute,
  } as any)
const Authenticated_adminAdminDataPohonAddIndexRoute =
  Authenticated_adminAdminDataPohonAddIndexRouteImport.update({
    id: '/admin/data/pohon/add/',
    path: '/admin/data/pohon/add/',
    getParentRoute: () => Authenticated_adminRoute,
  } as any)
const Authenticated_adminAdminDataPohonTreeIdIndexRoute =
  Authenticated_adminAdminDataPohonTreeIdIndexRouteImport.update({
    id: '/admin/data/pohon/$treeId/',
    path: '/admin/data/pohon/$treeId/',
    getParentRoute: () => Authenticated_adminRoute,
  } as any)
const Authenticated_adminAdminDataPatokBatasAddIndexRoute =
  Authenticated_adminAdminDataPatokBatasAddIndexRouteImport.update({
    id: '/admin/data/patok-batas/add/',
    path: '/admin/data/patok-batas/add/',
    getParentRoute: () => Authenticated_adminRoute,
  } as any)
const Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdIndexRoute =
  Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdIndexRouteImport.update(
    {
      id: '/admin/data/patok-batas/$boundaryMarkerId/',
      path: '/admin/data/patok-batas/$boundaryMarkerId/',
      getParentRoute: () => Authenticated_adminRoute,
    } as any,
  )
const Authenticated_adminAdminConfigUserAddIndexRoute =
  Authenticated_adminAdminConfigUserAddIndexRouteImport.update({
    id: '/admin/config/user/add/',
    path: '/admin/config/user/add/',
    getParentRoute: () => Authenticated_adminRoute,
  } as any)
const Authenticated_adminAdminMasterPohonUpdateMasterTreeIdRoute =
  Authenticated_adminAdminMasterPohonUpdateMasterTreeIdRouteImport.update({
    id: '/admin/master/pohon/update/$masterTreeId',
    path: '/admin/master/pohon/update/$masterTreeId',
    getParentRoute: () => Authenticated_adminRoute,
  } as any)
const Authenticated_adminAdminMasterPohonLokalUpdateMasterLocalTreeIdRoute =
  Authenticated_adminAdminMasterPohonLokalUpdateMasterLocalTreeIdRouteImport.update(
    {
      id: '/admin/master/pohon-lokal/update/$masterLocalTreeId',
      path: '/admin/master/pohon-lokal/update/$masterLocalTreeId',
      getParentRoute: () => Authenticated_adminRoute,
    } as any,
  )
const Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdUpdateKomunitasIndexRoute =
  Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdUpdateKomunitasIndexRouteImport.update(
    {
      id: '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/update-komunitas/',
      path: '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/update-komunitas/',
      getParentRoute: () => Authenticated_adminRoute,
    } as any,
  )
const Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAllPhotosIndexRoute =
  Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAllPhotosIndexRouteImport.update(
    {
      id: '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/all-photos/',
      path: '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/all-photos/',
      getParentRoute: () => Authenticated_adminRoute,
    } as any,
  )
const Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasIndexRoute =
  Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasIndexRouteImport.update(
    {
      id: '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/',
      path: '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/',
      getParentRoute: () => Authenticated_adminRoute,
    } as any,
  )
const Authenticated_adminAdminMasterKodePatokBatasBoundaryMarkerCodeIdUpdateIndexRoute =
  Authenticated_adminAdminMasterKodePatokBatasBoundaryMarkerCodeIdUpdateIndexRouteImport.update(
    {
      id: '/admin/master/kode-patok-batas/$boundaryMarkerCodeId/update/',
      path: '/admin/master/kode-patok-batas/$boundaryMarkerCodeId/update/',
      getParentRoute: () => Authenticated_adminRoute,
    } as any,
  )
const Authenticated_adminAdminDataPohonTreeIdUpdateIndexRoute =
  Authenticated_adminAdminDataPohonTreeIdUpdateIndexRouteImport.update({
    id: '/admin/data/pohon/$treeId/update/',
    path: '/admin/data/pohon/$treeId/update/',
    getParentRoute: () => Authenticated_adminRoute,
  } as any)
const Authenticated_adminAdminDataPohonTreeIdSurveyHistoryIndexRoute =
  Authenticated_adminAdminDataPohonTreeIdSurveyHistoryIndexRouteImport.update({
    id: '/admin/data/pohon/$treeId/survey-history/',
    path: '/admin/data/pohon/$treeId/survey-history/',
    getParentRoute: () => Authenticated_adminRoute,
  } as any)
const Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdUpdateIndexRoute =
  Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdUpdateIndexRouteImport.update(
    {
      id: '/admin/data/patok-batas/$boundaryMarkerId/update/',
      path: '/admin/data/patok-batas/$boundaryMarkerId/update/',
      getParentRoute: () => Authenticated_adminRoute,
    } as any,
  )
const Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdCheckHistoryIndexRoute =
  Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdCheckHistoryIndexRouteImport.update(
    {
      id: '/admin/data/patok-batas/$boundaryMarkerId/check-history/',
      path: '/admin/data/patok-batas/$boundaryMarkerId/check-history/',
      getParentRoute: () => Authenticated_adminRoute,
    } as any,
  )
const Authenticated_adminAdminConfigUserUserIdUpdateIndexRoute =
  Authenticated_adminAdminConfigUserUserIdUpdateIndexRouteImport.update({
    id: '/admin/config/user/$userId/update/',
    path: '/admin/config/user/$userId/update/',
    getParentRoute: () => Authenticated_adminRoute,
  } as any)
const Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasAddIndexRoute =
  Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasAddIndexRouteImport.update(
    {
      id: '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/add/',
      path: '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/add/',
      getParentRoute: () => Authenticated_adminRoute,
    } as any,
  )
const Authenticated_adminAdminDataPohonTreeIdSurveyHistoryAddIndexRoute =
  Authenticated_adminAdminDataPohonTreeIdSurveyHistoryAddIndexRouteImport.update(
    {
      id: '/admin/data/pohon/$treeId/survey-history/add/',
      path: '/admin/data/pohon/$treeId/survey-history/add/',
      getParentRoute: () => Authenticated_adminRoute,
    } as any,
  )
const Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdCheckHistoryAddIndexRoute =
  Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdCheckHistoryAddIndexRouteImport.update(
    {
      id: '/admin/data/patok-batas/$boundaryMarkerId/check-history/add/',
      path: '/admin/data/patok-batas/$boundaryMarkerId/check-history/add/',
      getParentRoute: () => Authenticated_adminRoute,
    } as any,
  )
const Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasGroupActivityIdUpdateIndexRoute =
  Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasGroupActivityIdUpdateIndexRouteImport.update(
    {
      id: '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/$groupActivityId/update/',
      path: '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/$groupActivityId/update/',
      getParentRoute: () => Authenticated_adminRoute,
    } as any,
  )
const Authenticated_adminAdminDataPohonTreeIdSurveyHistorySurveyHistoryIdUpdateIndexRoute =
  Authenticated_adminAdminDataPohonTreeIdSurveyHistorySurveyHistoryIdUpdateIndexRouteImport.update(
    {
      id: '/admin/data/pohon/$treeId/survey-history/$surveyHistoryId/update/',
      path: '/admin/data/pohon/$treeId/survey-history/$surveyHistoryId/update/',
      getParentRoute: () => Authenticated_adminRoute,
    } as any,
  )
const Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdCheckHistoryCheckBmHistoryIdUpdateIndexRoute =
  Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdCheckHistoryCheckBmHistoryIdUpdateIndexRouteImport.update(
    {
      id: '/admin/data/patok-batas/$boundaryMarkerId/check-history/$checkBmHistoryId/update/',
      path: '/admin/data/patok-batas/$boundaryMarkerId/check-history/$checkBmHistoryId/update/',
      getParentRoute: () => Authenticated_adminRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/register': typeof RegisterRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/': typeof AuthenticatedIndexRoute
  '/tentang-kami': typeof TentangKamiIndexRoute
  '/admin/profile': typeof Authenticated_adminAdminProfileRoute
  '/pemetaan': typeof AuthenticatedPemetaanIndexRoute
  '/program-kami': typeof AuthenticatedProgramKamiIndexRoute
  '/admin': typeof Authenticated_adminAdminIndexRoute
  '/tentang-kami/apa-itu-adopsi-pohon': typeof TentangKamiApaItuAdopsiPohonIndexRoute
  '/tentang-kami/kelompok-komunitas/$kelompokKomunitasName': typeof AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasNameRoute
  '/data/pohon': typeof AuthenticatedDataPohonIndexRoute
  '/program-kami/adopsi-pohon': typeof AuthenticatedProgramKamiAdopsiPohonIndexRoute
  '/program-kami/monitor-biodiversity': typeof AuthenticatedProgramKamiMonitorBiodiversityIndexRoute
  '/program-kami/patroli-&-geo-tagging': typeof AuthenticatedProgramKamiPatroliChar38GeoTaggingIndexRoute
  '/program-kami/pemberdayaan-masyarakat': typeof AuthenticatedProgramKamiPemberdayaanMasyarakatIndexRoute
  '/tentang-kami/kelompok-komunitas': typeof AuthenticatedTentangKamiKelompokKomunitasIndexRoute
  '/admin/pemetaan': typeof Authenticated_adminAdminPemetaanIndexRoute
  '/admin/master/pohon/add-master-tree': typeof Authenticated_adminAdminMasterPohonAddMasterTreeRoute
  '/admin/tentang-kami/kelompok-komunitas/add-komunitas': typeof Authenticated_adminAdminTentangKamiKelompokKomunitasAddKomunitasRoute
  '/data/pohon/$treeId': typeof AuthenticatedDataPohonTreeIdIndexRoute
  '/admin/config/role-permission': typeof Authenticated_adminAdminConfigRolePermissionIndexRoute
  '/admin/config/user': typeof Authenticated_adminAdminConfigUserIndexRoute
  '/admin/data/patok-batas': typeof Authenticated_adminAdminDataPatokBatasIndexRoute
  '/admin/data/pohon': typeof Authenticated_adminAdminDataPohonIndexRoute
  '/admin/master/kode-patok-batas': typeof Authenticated_adminAdminMasterKodePatokBatasIndexRoute
  '/admin/master/pohon-lokal': typeof Authenticated_adminAdminMasterPohonLokalIndexRoute
  '/admin/master/pohon': typeof Authenticated_adminAdminMasterPohonIndexRoute
  '/admin/tentang-kami/kelompok-komunitas': typeof Authenticated_adminAdminTentangKamiKelompokKomunitasIndexRoute
  '/admin/master/pohon-lokal/update/$masterLocalTreeId': typeof Authenticated_adminAdminMasterPohonLokalUpdateMasterLocalTreeIdRoute
  '/admin/master/pohon/update/$masterTreeId': typeof Authenticated_adminAdminMasterPohonUpdateMasterTreeIdRoute
  '/admin/config/user/add': typeof Authenticated_adminAdminConfigUserAddIndexRoute
  '/admin/data/patok-batas/$boundaryMarkerId': typeof Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdIndexRoute
  '/admin/data/patok-batas/add': typeof Authenticated_adminAdminDataPatokBatasAddIndexRoute
  '/admin/data/pohon/$treeId': typeof Authenticated_adminAdminDataPohonTreeIdIndexRoute
  '/admin/data/pohon/add': typeof Authenticated_adminAdminDataPohonAddIndexRoute
  '/admin/master/kode-patok-batas/add': typeof Authenticated_adminAdminMasterKodePatokBatasAddIndexRoute
  '/admin/master/pohon-lokal/add': typeof Authenticated_adminAdminMasterPohonLokalAddIndexRoute
  '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId': typeof Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdIndexRoute
  '/admin/config/user/$userId/update': typeof Authenticated_adminAdminConfigUserUserIdUpdateIndexRoute
  '/admin/data/patok-batas/$boundaryMarkerId/check-history': typeof Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdCheckHistoryIndexRoute
  '/admin/data/patok-batas/$boundaryMarkerId/update': typeof Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdUpdateIndexRoute
  '/admin/data/pohon/$treeId/survey-history': typeof Authenticated_adminAdminDataPohonTreeIdSurveyHistoryIndexRoute
  '/admin/data/pohon/$treeId/update': typeof Authenticated_adminAdminDataPohonTreeIdUpdateIndexRoute
  '/admin/master/kode-patok-batas/$boundaryMarkerCodeId/update': typeof Authenticated_adminAdminMasterKodePatokBatasBoundaryMarkerCodeIdUpdateIndexRoute
  '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas': typeof Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasIndexRoute
  '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/all-photos': typeof Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAllPhotosIndexRoute
  '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/update-komunitas': typeof Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdUpdateKomunitasIndexRoute
  '/admin/data/patok-batas/$boundaryMarkerId/check-history/add': typeof Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdCheckHistoryAddIndexRoute
  '/admin/data/pohon/$treeId/survey-history/add': typeof Authenticated_adminAdminDataPohonTreeIdSurveyHistoryAddIndexRoute
  '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/add': typeof Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasAddIndexRoute
  '/admin/data/patok-batas/$boundaryMarkerId/check-history/$checkBmHistoryId/update': typeof Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdCheckHistoryCheckBmHistoryIdUpdateIndexRoute
  '/admin/data/pohon/$treeId/survey-history/$surveyHistoryId/update': typeof Authenticated_adminAdminDataPohonTreeIdSurveyHistorySurveyHistoryIdUpdateIndexRoute
  '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/$groupActivityId/update': typeof Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasGroupActivityIdUpdateIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/register': typeof RegisterRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/': typeof AuthenticatedIndexRoute
  '/tentang-kami': typeof TentangKamiIndexRoute
  '/admin/profile': typeof Authenticated_adminAdminProfileRoute
  '/pemetaan': typeof AuthenticatedPemetaanIndexRoute
  '/program-kami': typeof AuthenticatedProgramKamiIndexRoute
  '/admin': typeof Authenticated_adminAdminIndexRoute
  '/tentang-kami/apa-itu-adopsi-pohon': typeof TentangKamiApaItuAdopsiPohonIndexRoute
  '/tentang-kami/kelompok-komunitas/$kelompokKomunitasName': typeof AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasNameRoute
  '/data/pohon': typeof AuthenticatedDataPohonIndexRoute
  '/program-kami/adopsi-pohon': typeof AuthenticatedProgramKamiAdopsiPohonIndexRoute
  '/program-kami/monitor-biodiversity': typeof AuthenticatedProgramKamiMonitorBiodiversityIndexRoute
  '/program-kami/patroli-&-geo-tagging': typeof AuthenticatedProgramKamiPatroliChar38GeoTaggingIndexRoute
  '/program-kami/pemberdayaan-masyarakat': typeof AuthenticatedProgramKamiPemberdayaanMasyarakatIndexRoute
  '/tentang-kami/kelompok-komunitas': typeof AuthenticatedTentangKamiKelompokKomunitasIndexRoute
  '/admin/pemetaan': typeof Authenticated_adminAdminPemetaanIndexRoute
  '/admin/master/pohon/add-master-tree': typeof Authenticated_adminAdminMasterPohonAddMasterTreeRoute
  '/admin/tentang-kami/kelompok-komunitas/add-komunitas': typeof Authenticated_adminAdminTentangKamiKelompokKomunitasAddKomunitasRoute
  '/data/pohon/$treeId': typeof AuthenticatedDataPohonTreeIdIndexRoute
  '/admin/config/role-permission': typeof Authenticated_adminAdminConfigRolePermissionIndexRoute
  '/admin/config/user': typeof Authenticated_adminAdminConfigUserIndexRoute
  '/admin/data/patok-batas': typeof Authenticated_adminAdminDataPatokBatasIndexRoute
  '/admin/data/pohon': typeof Authenticated_adminAdminDataPohonIndexRoute
  '/admin/master/kode-patok-batas': typeof Authenticated_adminAdminMasterKodePatokBatasIndexRoute
  '/admin/master/pohon-lokal': typeof Authenticated_adminAdminMasterPohonLokalIndexRoute
  '/admin/master/pohon': typeof Authenticated_adminAdminMasterPohonIndexRoute
  '/admin/tentang-kami/kelompok-komunitas': typeof Authenticated_adminAdminTentangKamiKelompokKomunitasIndexRoute
  '/admin/master/pohon-lokal/update/$masterLocalTreeId': typeof Authenticated_adminAdminMasterPohonLokalUpdateMasterLocalTreeIdRoute
  '/admin/master/pohon/update/$masterTreeId': typeof Authenticated_adminAdminMasterPohonUpdateMasterTreeIdRoute
  '/admin/config/user/add': typeof Authenticated_adminAdminConfigUserAddIndexRoute
  '/admin/data/patok-batas/$boundaryMarkerId': typeof Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdIndexRoute
  '/admin/data/patok-batas/add': typeof Authenticated_adminAdminDataPatokBatasAddIndexRoute
  '/admin/data/pohon/$treeId': typeof Authenticated_adminAdminDataPohonTreeIdIndexRoute
  '/admin/data/pohon/add': typeof Authenticated_adminAdminDataPohonAddIndexRoute
  '/admin/master/kode-patok-batas/add': typeof Authenticated_adminAdminMasterKodePatokBatasAddIndexRoute
  '/admin/master/pohon-lokal/add': typeof Authenticated_adminAdminMasterPohonLokalAddIndexRoute
  '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId': typeof Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdIndexRoute
  '/admin/config/user/$userId/update': typeof Authenticated_adminAdminConfigUserUserIdUpdateIndexRoute
  '/admin/data/patok-batas/$boundaryMarkerId/check-history': typeof Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdCheckHistoryIndexRoute
  '/admin/data/patok-batas/$boundaryMarkerId/update': typeof Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdUpdateIndexRoute
  '/admin/data/pohon/$treeId/survey-history': typeof Authenticated_adminAdminDataPohonTreeIdSurveyHistoryIndexRoute
  '/admin/data/pohon/$treeId/update': typeof Authenticated_adminAdminDataPohonTreeIdUpdateIndexRoute
  '/admin/master/kode-patok-batas/$boundaryMarkerCodeId/update': typeof Authenticated_adminAdminMasterKodePatokBatasBoundaryMarkerCodeIdUpdateIndexRoute
  '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas': typeof Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasIndexRoute
  '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/all-photos': typeof Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAllPhotosIndexRoute
  '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/update-komunitas': typeof Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdUpdateKomunitasIndexRoute
  '/admin/data/patok-batas/$boundaryMarkerId/check-history/add': typeof Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdCheckHistoryAddIndexRoute
  '/admin/data/pohon/$treeId/survey-history/add': typeof Authenticated_adminAdminDataPohonTreeIdSurveyHistoryAddIndexRoute
  '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/add': typeof Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasAddIndexRoute
  '/admin/data/patok-batas/$boundaryMarkerId/check-history/$checkBmHistoryId/update': typeof Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdCheckHistoryCheckBmHistoryIdUpdateIndexRoute
  '/admin/data/pohon/$treeId/survey-history/$surveyHistoryId/update': typeof Authenticated_adminAdminDataPohonTreeIdSurveyHistorySurveyHistoryIdUpdateIndexRoute
  '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/$groupActivityId/update': typeof Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasGroupActivityIdUpdateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated_admin': typeof Authenticated_adminRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/register': typeof RegisterRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/tentang-kami/': typeof TentangKamiIndexRoute
  '/_authenticated_admin/admin/profile': typeof Authenticated_adminAdminProfileRoute
  '/_authenticated/pemetaan/': typeof AuthenticatedPemetaanIndexRoute
  '/_authenticated/program-kami/': typeof AuthenticatedProgramKamiIndexRoute
  '/_authenticated_admin/admin/': typeof Authenticated_adminAdminIndexRoute
  '/tentang-kami/apa-itu-adopsi-pohon/': typeof TentangKamiApaItuAdopsiPohonIndexRoute
  '/_authenticated/tentang-kami/kelompok-komunitas/$kelompokKomunitasName': typeof AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasNameRoute
  '/_authenticated/data/pohon/': typeof AuthenticatedDataPohonIndexRoute
  '/_authenticated/program-kami/adopsi-pohon/': typeof AuthenticatedProgramKamiAdopsiPohonIndexRoute
  '/_authenticated/program-kami/monitor-biodiversity/': typeof AuthenticatedProgramKamiMonitorBiodiversityIndexRoute
  '/_authenticated/program-kami/patroli-&-geo-tagging/': typeof AuthenticatedProgramKamiPatroliChar38GeoTaggingIndexRoute
  '/_authenticated/program-kami/pemberdayaan-masyarakat/': typeof AuthenticatedProgramKamiPemberdayaanMasyarakatIndexRoute
  '/_authenticated/tentang-kami/kelompok-komunitas/': typeof AuthenticatedTentangKamiKelompokKomunitasIndexRoute
  '/_authenticated_admin/admin/pemetaan/': typeof Authenticated_adminAdminPemetaanIndexRoute
  '/_authenticated_admin/admin/master/pohon/add-master-tree': typeof Authenticated_adminAdminMasterPohonAddMasterTreeRoute
  '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/add-komunitas': typeof Authenticated_adminAdminTentangKamiKelompokKomunitasAddKomunitasRoute
  '/_authenticated/data/pohon/$treeId/': typeof AuthenticatedDataPohonTreeIdIndexRoute
  '/_authenticated_admin/admin/config/role-permission/': typeof Authenticated_adminAdminConfigRolePermissionIndexRoute
  '/_authenticated_admin/admin/config/user/': typeof Authenticated_adminAdminConfigUserIndexRoute
  '/_authenticated_admin/admin/data/patok-batas/': typeof Authenticated_adminAdminDataPatokBatasIndexRoute
  '/_authenticated_admin/admin/data/pohon/': typeof Authenticated_adminAdminDataPohonIndexRoute
  '/_authenticated_admin/admin/master/kode-patok-batas/': typeof Authenticated_adminAdminMasterKodePatokBatasIndexRoute
  '/_authenticated_admin/admin/master/pohon-lokal/': typeof Authenticated_adminAdminMasterPohonLokalIndexRoute
  '/_authenticated_admin/admin/master/pohon/': typeof Authenticated_adminAdminMasterPohonIndexRoute
  '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/': typeof Authenticated_adminAdminTentangKamiKelompokKomunitasIndexRoute
  '/_authenticated_admin/admin/master/pohon-lokal/update/$masterLocalTreeId': typeof Authenticated_adminAdminMasterPohonLokalUpdateMasterLocalTreeIdRoute
  '/_authenticated_admin/admin/master/pohon/update/$masterTreeId': typeof Authenticated_adminAdminMasterPohonUpdateMasterTreeIdRoute
  '/_authenticated_admin/admin/config/user/add/': typeof Authenticated_adminAdminConfigUserAddIndexRoute
  '/_authenticated_admin/admin/data/patok-batas/$boundaryMarkerId/': typeof Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdIndexRoute
  '/_authenticated_admin/admin/data/patok-batas/add/': typeof Authenticated_adminAdminDataPatokBatasAddIndexRoute
  '/_authenticated_admin/admin/data/pohon/$treeId/': typeof Authenticated_adminAdminDataPohonTreeIdIndexRoute
  '/_authenticated_admin/admin/data/pohon/add/': typeof Authenticated_adminAdminDataPohonAddIndexRoute
  '/_authenticated_admin/admin/master/kode-patok-batas/add/': typeof Authenticated_adminAdminMasterKodePatokBatasAddIndexRoute
  '/_authenticated_admin/admin/master/pohon-lokal/add/': typeof Authenticated_adminAdminMasterPohonLokalAddIndexRoute
  '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/': typeof Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdIndexRoute
  '/_authenticated_admin/admin/config/user/$userId/update/': typeof Authenticated_adminAdminConfigUserUserIdUpdateIndexRoute
  '/_authenticated_admin/admin/data/patok-batas/$boundaryMarkerId/check-history/': typeof Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdCheckHistoryIndexRoute
  '/_authenticated_admin/admin/data/patok-batas/$boundaryMarkerId/update/': typeof Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdUpdateIndexRoute
  '/_authenticated_admin/admin/data/pohon/$treeId/survey-history/': typeof Authenticated_adminAdminDataPohonTreeIdSurveyHistoryIndexRoute
  '/_authenticated_admin/admin/data/pohon/$treeId/update/': typeof Authenticated_adminAdminDataPohonTreeIdUpdateIndexRoute
  '/_authenticated_admin/admin/master/kode-patok-batas/$boundaryMarkerCodeId/update/': typeof Authenticated_adminAdminMasterKodePatokBatasBoundaryMarkerCodeIdUpdateIndexRoute
  '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/': typeof Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasIndexRoute
  '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/all-photos/': typeof Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAllPhotosIndexRoute
  '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/update-komunitas/': typeof Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdUpdateKomunitasIndexRoute
  '/_authenticated_admin/admin/data/patok-batas/$boundaryMarkerId/check-history/add/': typeof Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdCheckHistoryAddIndexRoute
  '/_authenticated_admin/admin/data/pohon/$treeId/survey-history/add/': typeof Authenticated_adminAdminDataPohonTreeIdSurveyHistoryAddIndexRoute
  '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/add/': typeof Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasAddIndexRoute
  '/_authenticated_admin/admin/data/patok-batas/$boundaryMarkerId/check-history/$checkBmHistoryId/update/': typeof Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdCheckHistoryCheckBmHistoryIdUpdateIndexRoute
  '/_authenticated_admin/admin/data/pohon/$treeId/survey-history/$surveyHistoryId/update/': typeof Authenticated_adminAdminDataPohonTreeIdSurveyHistorySurveyHistoryIdUpdateIndexRoute
  '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/$groupActivityId/update/': typeof Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasGroupActivityIdUpdateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/login'
    | '/not-found'
    | '/register'
    | '/profile'
    | '/'
    | '/tentang-kami'
    | '/admin/profile'
    | '/pemetaan'
    | '/program-kami'
    | '/admin'
    | '/tentang-kami/apa-itu-adopsi-pohon'
    | '/tentang-kami/kelompok-komunitas/$kelompokKomunitasName'
    | '/data/pohon'
    | '/program-kami/adopsi-pohon'
    | '/program-kami/monitor-biodiversity'
    | '/program-kami/patroli-&-geo-tagging'
    | '/program-kami/pemberdayaan-masyarakat'
    | '/tentang-kami/kelompok-komunitas'
    | '/admin/pemetaan'
    | '/admin/master/pohon/add-master-tree'
    | '/admin/tentang-kami/kelompok-komunitas/add-komunitas'
    | '/data/pohon/$treeId'
    | '/admin/config/role-permission'
    | '/admin/config/user'
    | '/admin/data/patok-batas'
    | '/admin/data/pohon'
    | '/admin/master/kode-patok-batas'
    | '/admin/master/pohon-lokal'
    | '/admin/master/pohon'
    | '/admin/tentang-kami/kelompok-komunitas'
    | '/admin/master/pohon-lokal/update/$masterLocalTreeId'
    | '/admin/master/pohon/update/$masterTreeId'
    | '/admin/config/user/add'
    | '/admin/data/patok-batas/$boundaryMarkerId'
    | '/admin/data/patok-batas/add'
    | '/admin/data/pohon/$treeId'
    | '/admin/data/pohon/add'
    | '/admin/master/kode-patok-batas/add'
    | '/admin/master/pohon-lokal/add'
    | '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId'
    | '/admin/config/user/$userId/update'
    | '/admin/data/patok-batas/$boundaryMarkerId/check-history'
    | '/admin/data/patok-batas/$boundaryMarkerId/update'
    | '/admin/data/pohon/$treeId/survey-history'
    | '/admin/data/pohon/$treeId/update'
    | '/admin/master/kode-patok-batas/$boundaryMarkerCodeId/update'
    | '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas'
    | '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/all-photos'
    | '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/update-komunitas'
    | '/admin/data/patok-batas/$boundaryMarkerId/check-history/add'
    | '/admin/data/pohon/$treeId/survey-history/add'
    | '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/add'
    | '/admin/data/patok-batas/$boundaryMarkerId/check-history/$checkBmHistoryId/update'
    | '/admin/data/pohon/$treeId/survey-history/$surveyHistoryId/update'
    | '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/$groupActivityId/update'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/login'
    | '/not-found'
    | '/register'
    | '/profile'
    | '/'
    | '/tentang-kami'
    | '/admin/profile'
    | '/pemetaan'
    | '/program-kami'
    | '/admin'
    | '/tentang-kami/apa-itu-adopsi-pohon'
    | '/tentang-kami/kelompok-komunitas/$kelompokKomunitasName'
    | '/data/pohon'
    | '/program-kami/adopsi-pohon'
    | '/program-kami/monitor-biodiversity'
    | '/program-kami/patroli-&-geo-tagging'
    | '/program-kami/pemberdayaan-masyarakat'
    | '/tentang-kami/kelompok-komunitas'
    | '/admin/pemetaan'
    | '/admin/master/pohon/add-master-tree'
    | '/admin/tentang-kami/kelompok-komunitas/add-komunitas'
    | '/data/pohon/$treeId'
    | '/admin/config/role-permission'
    | '/admin/config/user'
    | '/admin/data/patok-batas'
    | '/admin/data/pohon'
    | '/admin/master/kode-patok-batas'
    | '/admin/master/pohon-lokal'
    | '/admin/master/pohon'
    | '/admin/tentang-kami/kelompok-komunitas'
    | '/admin/master/pohon-lokal/update/$masterLocalTreeId'
    | '/admin/master/pohon/update/$masterTreeId'
    | '/admin/config/user/add'
    | '/admin/data/patok-batas/$boundaryMarkerId'
    | '/admin/data/patok-batas/add'
    | '/admin/data/pohon/$treeId'
    | '/admin/data/pohon/add'
    | '/admin/master/kode-patok-batas/add'
    | '/admin/master/pohon-lokal/add'
    | '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId'
    | '/admin/config/user/$userId/update'
    | '/admin/data/patok-batas/$boundaryMarkerId/check-history'
    | '/admin/data/patok-batas/$boundaryMarkerId/update'
    | '/admin/data/pohon/$treeId/survey-history'
    | '/admin/data/pohon/$treeId/update'
    | '/admin/master/kode-patok-batas/$boundaryMarkerCodeId/update'
    | '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas'
    | '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/all-photos'
    | '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/update-komunitas'
    | '/admin/data/patok-batas/$boundaryMarkerId/check-history/add'
    | '/admin/data/pohon/$treeId/survey-history/add'
    | '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/add'
    | '/admin/data/patok-batas/$boundaryMarkerId/check-history/$checkBmHistoryId/update'
    | '/admin/data/pohon/$treeId/survey-history/$surveyHistoryId/update'
    | '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/$groupActivityId/update'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated_admin'
    | '/about'
    | '/login'
    | '/not-found'
    | '/register'
    | '/_authenticated/profile'
    | '/_authenticated/'
    | '/tentang-kami/'
    | '/_authenticated_admin/admin/profile'
    | '/_authenticated/pemetaan/'
    | '/_authenticated/program-kami/'
    | '/_authenticated_admin/admin/'
    | '/tentang-kami/apa-itu-adopsi-pohon/'
    | '/_authenticated/tentang-kami/kelompok-komunitas/$kelompokKomunitasName'
    | '/_authenticated/data/pohon/'
    | '/_authenticated/program-kami/adopsi-pohon/'
    | '/_authenticated/program-kami/monitor-biodiversity/'
    | '/_authenticated/program-kami/patroli-&-geo-tagging/'
    | '/_authenticated/program-kami/pemberdayaan-masyarakat/'
    | '/_authenticated/tentang-kami/kelompok-komunitas/'
    | '/_authenticated_admin/admin/pemetaan/'
    | '/_authenticated_admin/admin/master/pohon/add-master-tree'
    | '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/add-komunitas'
    | '/_authenticated/data/pohon/$treeId/'
    | '/_authenticated_admin/admin/config/role-permission/'
    | '/_authenticated_admin/admin/config/user/'
    | '/_authenticated_admin/admin/data/patok-batas/'
    | '/_authenticated_admin/admin/data/pohon/'
    | '/_authenticated_admin/admin/master/kode-patok-batas/'
    | '/_authenticated_admin/admin/master/pohon-lokal/'
    | '/_authenticated_admin/admin/master/pohon/'
    | '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/'
    | '/_authenticated_admin/admin/master/pohon-lokal/update/$masterLocalTreeId'
    | '/_authenticated_admin/admin/master/pohon/update/$masterTreeId'
    | '/_authenticated_admin/admin/config/user/add/'
    | '/_authenticated_admin/admin/data/patok-batas/$boundaryMarkerId/'
    | '/_authenticated_admin/admin/data/patok-batas/add/'
    | '/_authenticated_admin/admin/data/pohon/$treeId/'
    | '/_authenticated_admin/admin/data/pohon/add/'
    | '/_authenticated_admin/admin/master/kode-patok-batas/add/'
    | '/_authenticated_admin/admin/master/pohon-lokal/add/'
    | '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/'
    | '/_authenticated_admin/admin/config/user/$userId/update/'
    | '/_authenticated_admin/admin/data/patok-batas/$boundaryMarkerId/check-history/'
    | '/_authenticated_admin/admin/data/patok-batas/$boundaryMarkerId/update/'
    | '/_authenticated_admin/admin/data/pohon/$treeId/survey-history/'
    | '/_authenticated_admin/admin/data/pohon/$treeId/update/'
    | '/_authenticated_admin/admin/master/kode-patok-batas/$boundaryMarkerCodeId/update/'
    | '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/'
    | '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/all-photos/'
    | '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/update-komunitas/'
    | '/_authenticated_admin/admin/data/patok-batas/$boundaryMarkerId/check-history/add/'
    | '/_authenticated_admin/admin/data/pohon/$treeId/survey-history/add/'
    | '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/add/'
    | '/_authenticated_admin/admin/data/patok-batas/$boundaryMarkerId/check-history/$checkBmHistoryId/update/'
    | '/_authenticated_admin/admin/data/pohon/$treeId/survey-history/$surveyHistoryId/update/'
    | '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/$groupActivityId/update/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  Authenticated_adminRoute: typeof Authenticated_adminRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  NotFoundRoute: typeof NotFoundRoute
  RegisterRoute: typeof RegisterRoute
  TentangKamiIndexRoute: typeof TentangKamiIndexRoute
  TentangKamiApaItuAdopsiPohonIndexRoute: typeof TentangKamiApaItuAdopsiPohonIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated_admin': {
      id: '/_authenticated_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof Authenticated_adminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang-kami/': {
      id: '/tentang-kami/'
      path: '/tentang-kami'
      fullPath: '/tentang-kami'
      preLoaderRoute: typeof TentangKamiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/tentang-kami/apa-itu-adopsi-pohon/': {
      id: '/tentang-kami/apa-itu-adopsi-pohon/'
      path: '/tentang-kami/apa-itu-adopsi-pohon'
      fullPath: '/tentang-kami/apa-itu-adopsi-pohon'
      preLoaderRoute: typeof TentangKamiApaItuAdopsiPohonIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated_admin/admin/': {
      id: '/_authenticated_admin/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof Authenticated_adminAdminIndexRouteImport
      parentRoute: typeof Authenticated_adminRoute
    }
    '/_authenticated/program-kami/': {
      id: '/_authenticated/program-kami/'
      path: '/program-kami'
      fullPath: '/program-kami'
      preLoaderRoute: typeof AuthenticatedProgramKamiIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pemetaan/': {
      id: '/_authenticated/pemetaan/'
      path: '/pemetaan'
      fullPath: '/pemetaan'
      preLoaderRoute: typeof AuthenticatedPemetaanIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated_admin/admin/profile': {
      id: '/_authenticated_admin/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof Authenticated_adminAdminProfileRouteImport
      parentRoute: typeof Authenticated_adminRoute
    }
    '/_authenticated_admin/admin/pemetaan/': {
      id: '/_authenticated_admin/admin/pemetaan/'
      path: '/admin/pemetaan'
      fullPath: '/admin/pemetaan'
      preLoaderRoute: typeof Authenticated_adminAdminPemetaanIndexRouteImport
      parentRoute: typeof Authenticated_adminRoute
    }
    '/_authenticated/tentang-kami/kelompok-komunitas/': {
      id: '/_authenticated/tentang-kami/kelompok-komunitas/'
      path: '/tentang-kami/kelompok-komunitas'
      fullPath: '/tentang-kami/kelompok-komunitas'
      preLoaderRoute: typeof AuthenticatedTentangKamiKelompokKomunitasIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/program-kami/pemberdayaan-masyarakat/': {
      id: '/_authenticated/program-kami/pemberdayaan-masyarakat/'
      path: '/program-kami/pemberdayaan-masyarakat'
      fullPath: '/program-kami/pemberdayaan-masyarakat'
      preLoaderRoute: typeof AuthenticatedProgramKamiPemberdayaanMasyarakatIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/program-kami/patroli-&-geo-tagging/': {
      id: '/_authenticated/program-kami/patroli-&-geo-tagging/'
      path: '/program-kami/patroli-&-geo-tagging'
      fullPath: '/program-kami/patroli-&-geo-tagging'
      preLoaderRoute: typeof AuthenticatedProgramKamiPatroliChar38GeoTaggingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/program-kami/monitor-biodiversity/': {
      id: '/_authenticated/program-kami/monitor-biodiversity/'
      path: '/program-kami/monitor-biodiversity'
      fullPath: '/program-kami/monitor-biodiversity'
      preLoaderRoute: typeof AuthenticatedProgramKamiMonitorBiodiversityIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/program-kami/adopsi-pohon/': {
      id: '/_authenticated/program-kami/adopsi-pohon/'
      path: '/program-kami/adopsi-pohon'
      fullPath: '/program-kami/adopsi-pohon'
      preLoaderRoute: typeof AuthenticatedProgramKamiAdopsiPohonIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/data/pohon/': {
      id: '/_authenticated/data/pohon/'
      path: '/data/pohon'
      fullPath: '/data/pohon'
      preLoaderRoute: typeof AuthenticatedDataPohonIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tentang-kami/kelompok-komunitas/$kelompokKomunitasName': {
      id: '/_authenticated/tentang-kami/kelompok-komunitas/$kelompokKomunitasName'
      path: '/tentang-kami/kelompok-komunitas/$kelompokKomunitasName'
      fullPath: '/tentang-kami/kelompok-komunitas/$kelompokKomunitasName'
      preLoaderRoute: typeof AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasNameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/': {
      id: '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/'
      path: '/admin/tentang-kami/kelompok-komunitas'
      fullPath: '/admin/tentang-kami/kelompok-komunitas'
      preLoaderRoute: typeof Authenticated_adminAdminTentangKamiKelompokKomunitasIndexRouteImport
      parentRoute: typeof Authenticated_adminRoute
    }
    '/_authenticated_admin/admin/master/pohon/': {
      id: '/_authenticated_admin/admin/master/pohon/'
      path: '/admin/master/pohon'
      fullPath: '/admin/master/pohon'
      preLoaderRoute: typeof Authenticated_adminAdminMasterPohonIndexRouteImport
      parentRoute: typeof Authenticated_adminRoute
    }
    '/_authenticated_admin/admin/master/pohon-lokal/': {
      id: '/_authenticated_admin/admin/master/pohon-lokal/'
      path: '/admin/master/pohon-lokal'
      fullPath: '/admin/master/pohon-lokal'
      preLoaderRoute: typeof Authenticated_adminAdminMasterPohonLokalIndexRouteImport
      parentRoute: typeof Authenticated_adminRoute
    }
    '/_authenticated_admin/admin/master/kode-patok-batas/': {
      id: '/_authenticated_admin/admin/master/kode-patok-batas/'
      path: '/admin/master/kode-patok-batas'
      fullPath: '/admin/master/kode-patok-batas'
      preLoaderRoute: typeof Authenticated_adminAdminMasterKodePatokBatasIndexRouteImport
      parentRoute: typeof Authenticated_adminRoute
    }
    '/_authenticated_admin/admin/data/pohon/': {
      id: '/_authenticated_admin/admin/data/pohon/'
      path: '/admin/data/pohon'
      fullPath: '/admin/data/pohon'
      preLoaderRoute: typeof Authenticated_adminAdminDataPohonIndexRouteImport
      parentRoute: typeof Authenticated_adminRoute
    }
    '/_authenticated_admin/admin/data/patok-batas/': {
      id: '/_authenticated_admin/admin/data/patok-batas/'
      path: '/admin/data/patok-batas'
      fullPath: '/admin/data/patok-batas'
      preLoaderRoute: typeof Authenticated_adminAdminDataPatokBatasIndexRouteImport
      parentRoute: typeof Authenticated_adminRoute
    }
    '/_authenticated_admin/admin/config/user/': {
      id: '/_authenticated_admin/admin/config/user/'
      path: '/admin/config/user'
      fullPath: '/admin/config/user'
      preLoaderRoute: typeof Authenticated_adminAdminConfigUserIndexRouteImport
      parentRoute: typeof Authenticated_adminRoute
    }
    '/_authenticated_admin/admin/config/role-permission/': {
      id: '/_authenticated_admin/admin/config/role-permission/'
      path: '/admin/config/role-permission'
      fullPath: '/admin/config/role-permission'
      preLoaderRoute: typeof Authenticated_adminAdminConfigRolePermissionIndexRouteImport
      parentRoute: typeof Authenticated_adminRoute
    }
    '/_authenticated/data/pohon/$treeId/': {
      id: '/_authenticated/data/pohon/$treeId/'
      path: '/data/pohon/$treeId'
      fullPath: '/data/pohon/$treeId'
      preLoaderRoute: typeof AuthenticatedDataPohonTreeIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/add-komunitas': {
      id: '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/add-komunitas'
      path: '/admin/tentang-kami/kelompok-komunitas/add-komunitas'
      fullPath: '/admin/tentang-kami/kelompok-komunitas/add-komunitas'
      preLoaderRoute: typeof Authenticated_adminAdminTentangKamiKelompokKomunitasAddKomunitasRouteImport
      parentRoute: typeof Authenticated_adminRoute
    }
    '/_authenticated_admin/admin/master/pohon/add-master-tree': {
      id: '/_authenticated_admin/admin/master/pohon/add-master-tree'
      path: '/admin/master/pohon/add-master-tree'
      fullPath: '/admin/master/pohon/add-master-tree'
      preLoaderRoute: typeof Authenticated_adminAdminMasterPohonAddMasterTreeRouteImport
      parentRoute: typeof Authenticated_adminRoute
    }
    '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/': {
      id: '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/'
      path: '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId'
      fullPath: '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId'
      preLoaderRoute: typeof Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdIndexRouteImport
      parentRoute: typeof Authenticated_adminRoute
    }
    '/_authenticated_admin/admin/master/pohon-lokal/add/': {
      id: '/_authenticated_admin/admin/master/pohon-lokal/add/'
      path: '/admin/master/pohon-lokal/add'
      fullPath: '/admin/master/pohon-lokal/add'
      preLoaderRoute: typeof Authenticated_adminAdminMasterPohonLokalAddIndexRouteImport
      parentRoute: typeof Authenticated_adminRoute
    }
    '/_authenticated_admin/admin/master/kode-patok-batas/add/': {
      id: '/_authenticated_admin/admin/master/kode-patok-batas/add/'
      path: '/admin/master/kode-patok-batas/add'
      fullPath: '/admin/master/kode-patok-batas/add'
      preLoaderRoute: typeof Authenticated_adminAdminMasterKodePatokBatasAddIndexRouteImport
      parentRoute: typeof Authenticated_adminRoute
    }
    '/_authenticated_admin/admin/data/pohon/add/': {
      id: '/_authenticated_admin/admin/data/pohon/add/'
      path: '/admin/data/pohon/add'
      fullPath: '/admin/data/pohon/add'
      preLoaderRoute: typeof Authenticated_adminAdminDataPohonAddIndexRouteImport
      parentRoute: typeof Authenticated_adminRoute
    }
    '/_authenticated_admin/admin/data/pohon/$treeId/': {
      id: '/_authenticated_admin/admin/data/pohon/$treeId/'
      path: '/admin/data/pohon/$treeId'
      fullPath: '/admin/data/pohon/$treeId'
      preLoaderRoute: typeof Authenticated_adminAdminDataPohonTreeIdIndexRouteImport
      parentRoute: typeof Authenticated_adminRoute
    }
    '/_authenticated_admin/admin/data/patok-batas/add/': {
      id: '/_authenticated_admin/admin/data/patok-batas/add/'
      path: '/admin/data/patok-batas/add'
      fullPath: '/admin/data/patok-batas/add'
      preLoaderRoute: typeof Authenticated_adminAdminDataPatokBatasAddIndexRouteImport
      parentRoute: typeof Authenticated_adminRoute
    }
    '/_authenticated_admin/admin/data/patok-batas/$boundaryMarkerId/': {
      id: '/_authenticated_admin/admin/data/patok-batas/$boundaryMarkerId/'
      path: '/admin/data/patok-batas/$boundaryMarkerId'
      fullPath: '/admin/data/patok-batas/$boundaryMarkerId'
      preLoaderRoute: typeof Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdIndexRouteImport
      parentRoute: typeof Authenticated_adminRoute
    }
    '/_authenticated_admin/admin/config/user/add/': {
      id: '/_authenticated_admin/admin/config/user/add/'
      path: '/admin/config/user/add'
      fullPath: '/admin/config/user/add'
      preLoaderRoute: typeof Authenticated_adminAdminConfigUserAddIndexRouteImport
      parentRoute: typeof Authenticated_adminRoute
    }
    '/_authenticated_admin/admin/master/pohon/update/$masterTreeId': {
      id: '/_authenticated_admin/admin/master/pohon/update/$masterTreeId'
      path: '/admin/master/pohon/update/$masterTreeId'
      fullPath: '/admin/master/pohon/update/$masterTreeId'
      preLoaderRoute: typeof Authenticated_adminAdminMasterPohonUpdateMasterTreeIdRouteImport
      parentRoute: typeof Authenticated_adminRoute
    }
    '/_authenticated_admin/admin/master/pohon-lokal/update/$masterLocalTreeId': {
      id: '/_authenticated_admin/admin/master/pohon-lokal/update/$masterLocalTreeId'
      path: '/admin/master/pohon-lokal/update/$masterLocalTreeId'
      fullPath: '/admin/master/pohon-lokal/update/$masterLocalTreeId'
      preLoaderRoute: typeof Authenticated_adminAdminMasterPohonLokalUpdateMasterLocalTreeIdRouteImport
      parentRoute: typeof Authenticated_adminRoute
    }
    '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/update-komunitas/': {
      id: '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/update-komunitas/'
      path: '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/update-komunitas'
      fullPath: '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/update-komunitas'
      preLoaderRoute: typeof Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdUpdateKomunitasIndexRouteImport
      parentRoute: typeof Authenticated_adminRoute
    }
    '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/all-photos/': {
      id: '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/all-photos/'
      path: '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/all-photos'
      fullPath: '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/all-photos'
      preLoaderRoute: typeof Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAllPhotosIndexRouteImport
      parentRoute: typeof Authenticated_adminRoute
    }
    '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/': {
      id: '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/'
      path: '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas'
      fullPath: '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas'
      preLoaderRoute: typeof Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasIndexRouteImport
      parentRoute: typeof Authenticated_adminRoute
    }
    '/_authenticated_admin/admin/master/kode-patok-batas/$boundaryMarkerCodeId/update/': {
      id: '/_authenticated_admin/admin/master/kode-patok-batas/$boundaryMarkerCodeId/update/'
      path: '/admin/master/kode-patok-batas/$boundaryMarkerCodeId/update'
      fullPath: '/admin/master/kode-patok-batas/$boundaryMarkerCodeId/update'
      preLoaderRoute: typeof Authenticated_adminAdminMasterKodePatokBatasBoundaryMarkerCodeIdUpdateIndexRouteImport
      parentRoute: typeof Authenticated_adminRoute
    }
    '/_authenticated_admin/admin/data/pohon/$treeId/update/': {
      id: '/_authenticated_admin/admin/data/pohon/$treeId/update/'
      path: '/admin/data/pohon/$treeId/update'
      fullPath: '/admin/data/pohon/$treeId/update'
      preLoaderRoute: typeof Authenticated_adminAdminDataPohonTreeIdUpdateIndexRouteImport
      parentRoute: typeof Authenticated_adminRoute
    }
    '/_authenticated_admin/admin/data/pohon/$treeId/survey-history/': {
      id: '/_authenticated_admin/admin/data/pohon/$treeId/survey-history/'
      path: '/admin/data/pohon/$treeId/survey-history'
      fullPath: '/admin/data/pohon/$treeId/survey-history'
      preLoaderRoute: typeof Authenticated_adminAdminDataPohonTreeIdSurveyHistoryIndexRouteImport
      parentRoute: typeof Authenticated_adminRoute
    }
    '/_authenticated_admin/admin/data/patok-batas/$boundaryMarkerId/update/': {
      id: '/_authenticated_admin/admin/data/patok-batas/$boundaryMarkerId/update/'
      path: '/admin/data/patok-batas/$boundaryMarkerId/update'
      fullPath: '/admin/data/patok-batas/$boundaryMarkerId/update'
      preLoaderRoute: typeof Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdUpdateIndexRouteImport
      parentRoute: typeof Authenticated_adminRoute
    }
    '/_authenticated_admin/admin/data/patok-batas/$boundaryMarkerId/check-history/': {
      id: '/_authenticated_admin/admin/data/patok-batas/$boundaryMarkerId/check-history/'
      path: '/admin/data/patok-batas/$boundaryMarkerId/check-history'
      fullPath: '/admin/data/patok-batas/$boundaryMarkerId/check-history'
      preLoaderRoute: typeof Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdCheckHistoryIndexRouteImport
      parentRoute: typeof Authenticated_adminRoute
    }
    '/_authenticated_admin/admin/config/user/$userId/update/': {
      id: '/_authenticated_admin/admin/config/user/$userId/update/'
      path: '/admin/config/user/$userId/update'
      fullPath: '/admin/config/user/$userId/update'
      preLoaderRoute: typeof Authenticated_adminAdminConfigUserUserIdUpdateIndexRouteImport
      parentRoute: typeof Authenticated_adminRoute
    }
    '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/add/': {
      id: '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/add/'
      path: '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/add'
      fullPath: '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/add'
      preLoaderRoute: typeof Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasAddIndexRouteImport
      parentRoute: typeof Authenticated_adminRoute
    }
    '/_authenticated_admin/admin/data/pohon/$treeId/survey-history/add/': {
      id: '/_authenticated_admin/admin/data/pohon/$treeId/survey-history/add/'
      path: '/admin/data/pohon/$treeId/survey-history/add'
      fullPath: '/admin/data/pohon/$treeId/survey-history/add'
      preLoaderRoute: typeof Authenticated_adminAdminDataPohonTreeIdSurveyHistoryAddIndexRouteImport
      parentRoute: typeof Authenticated_adminRoute
    }
    '/_authenticated_admin/admin/data/patok-batas/$boundaryMarkerId/check-history/add/': {
      id: '/_authenticated_admin/admin/data/patok-batas/$boundaryMarkerId/check-history/add/'
      path: '/admin/data/patok-batas/$boundaryMarkerId/check-history/add'
      fullPath: '/admin/data/patok-batas/$boundaryMarkerId/check-history/add'
      preLoaderRoute: typeof Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdCheckHistoryAddIndexRouteImport
      parentRoute: typeof Authenticated_adminRoute
    }
    '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/$groupActivityId/update/': {
      id: '/_authenticated_admin/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/$groupActivityId/update/'
      path: '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/$groupActivityId/update'
      fullPath: '/admin/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/$groupActivityId/update'
      preLoaderRoute: typeof Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasGroupActivityIdUpdateIndexRouteImport
      parentRoute: typeof Authenticated_adminRoute
    }
    '/_authenticated_admin/admin/data/pohon/$treeId/survey-history/$surveyHistoryId/update/': {
      id: '/_authenticated_admin/admin/data/pohon/$treeId/survey-history/$surveyHistoryId/update/'
      path: '/admin/data/pohon/$treeId/survey-history/$surveyHistoryId/update'
      fullPath: '/admin/data/pohon/$treeId/survey-history/$surveyHistoryId/update'
      preLoaderRoute: typeof Authenticated_adminAdminDataPohonTreeIdSurveyHistorySurveyHistoryIdUpdateIndexRouteImport
      parentRoute: typeof Authenticated_adminRoute
    }
    '/_authenticated_admin/admin/data/patok-batas/$boundaryMarkerId/check-history/$checkBmHistoryId/update/': {
      id: '/_authenticated_admin/admin/data/patok-batas/$boundaryMarkerId/check-history/$checkBmHistoryId/update/'
      path: '/admin/data/patok-batas/$boundaryMarkerId/check-history/$checkBmHistoryId/update'
      fullPath: '/admin/data/patok-batas/$boundaryMarkerId/check-history/$checkBmHistoryId/update'
      preLoaderRoute: typeof Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdCheckHistoryCheckBmHistoryIdUpdateIndexRouteImport
      parentRoute: typeof Authenticated_adminRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPemetaanIndexRoute: typeof AuthenticatedPemetaanIndexRoute
  AuthenticatedProgramKamiIndexRoute: typeof AuthenticatedProgramKamiIndexRoute
  AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasNameRoute: typeof AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasNameRoute
  AuthenticatedDataPohonIndexRoute: typeof AuthenticatedDataPohonIndexRoute
  AuthenticatedProgramKamiAdopsiPohonIndexRoute: typeof AuthenticatedProgramKamiAdopsiPohonIndexRoute
  AuthenticatedProgramKamiMonitorBiodiversityIndexRoute: typeof AuthenticatedProgramKamiMonitorBiodiversityIndexRoute
  AuthenticatedProgramKamiPatroliChar38GeoTaggingIndexRoute: typeof AuthenticatedProgramKamiPatroliChar38GeoTaggingIndexRoute
  AuthenticatedProgramKamiPemberdayaanMasyarakatIndexRoute: typeof AuthenticatedProgramKamiPemberdayaanMasyarakatIndexRoute
  AuthenticatedTentangKamiKelompokKomunitasIndexRoute: typeof AuthenticatedTentangKamiKelompokKomunitasIndexRoute
  AuthenticatedDataPohonTreeIdIndexRoute: typeof AuthenticatedDataPohonTreeIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPemetaanIndexRoute: AuthenticatedPemetaanIndexRoute,
  AuthenticatedProgramKamiIndexRoute: AuthenticatedProgramKamiIndexRoute,
  AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasNameRoute:
    AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasNameRoute,
  AuthenticatedDataPohonIndexRoute: AuthenticatedDataPohonIndexRoute,
  AuthenticatedProgramKamiAdopsiPohonIndexRoute:
    AuthenticatedProgramKamiAdopsiPohonIndexRoute,
  AuthenticatedProgramKamiMonitorBiodiversityIndexRoute:
    AuthenticatedProgramKamiMonitorBiodiversityIndexRoute,
  AuthenticatedProgramKamiPatroliChar38GeoTaggingIndexRoute:
    AuthenticatedProgramKamiPatroliChar38GeoTaggingIndexRoute,
  AuthenticatedProgramKamiPemberdayaanMasyarakatIndexRoute:
    AuthenticatedProgramKamiPemberdayaanMasyarakatIndexRoute,
  AuthenticatedTentangKamiKelompokKomunitasIndexRoute:
    AuthenticatedTentangKamiKelompokKomunitasIndexRoute,
  AuthenticatedDataPohonTreeIdIndexRoute:
    AuthenticatedDataPohonTreeIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface Authenticated_adminRouteChildren {
  Authenticated_adminAdminProfileRoute: typeof Authenticated_adminAdminProfileRoute
  Authenticated_adminAdminIndexRoute: typeof Authenticated_adminAdminIndexRoute
  Authenticated_adminAdminPemetaanIndexRoute: typeof Authenticated_adminAdminPemetaanIndexRoute
  Authenticated_adminAdminMasterPohonAddMasterTreeRoute: typeof Authenticated_adminAdminMasterPohonAddMasterTreeRoute
  Authenticated_adminAdminTentangKamiKelompokKomunitasAddKomunitasRoute: typeof Authenticated_adminAdminTentangKamiKelompokKomunitasAddKomunitasRoute
  Authenticated_adminAdminConfigRolePermissionIndexRoute: typeof Authenticated_adminAdminConfigRolePermissionIndexRoute
  Authenticated_adminAdminConfigUserIndexRoute: typeof Authenticated_adminAdminConfigUserIndexRoute
  Authenticated_adminAdminDataPatokBatasIndexRoute: typeof Authenticated_adminAdminDataPatokBatasIndexRoute
  Authenticated_adminAdminDataPohonIndexRoute: typeof Authenticated_adminAdminDataPohonIndexRoute
  Authenticated_adminAdminMasterKodePatokBatasIndexRoute: typeof Authenticated_adminAdminMasterKodePatokBatasIndexRoute
  Authenticated_adminAdminMasterPohonLokalIndexRoute: typeof Authenticated_adminAdminMasterPohonLokalIndexRoute
  Authenticated_adminAdminMasterPohonIndexRoute: typeof Authenticated_adminAdminMasterPohonIndexRoute
  Authenticated_adminAdminTentangKamiKelompokKomunitasIndexRoute: typeof Authenticated_adminAdminTentangKamiKelompokKomunitasIndexRoute
  Authenticated_adminAdminMasterPohonLokalUpdateMasterLocalTreeIdRoute: typeof Authenticated_adminAdminMasterPohonLokalUpdateMasterLocalTreeIdRoute
  Authenticated_adminAdminMasterPohonUpdateMasterTreeIdRoute: typeof Authenticated_adminAdminMasterPohonUpdateMasterTreeIdRoute
  Authenticated_adminAdminConfigUserAddIndexRoute: typeof Authenticated_adminAdminConfigUserAddIndexRoute
  Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdIndexRoute: typeof Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdIndexRoute
  Authenticated_adminAdminDataPatokBatasAddIndexRoute: typeof Authenticated_adminAdminDataPatokBatasAddIndexRoute
  Authenticated_adminAdminDataPohonTreeIdIndexRoute: typeof Authenticated_adminAdminDataPohonTreeIdIndexRoute
  Authenticated_adminAdminDataPohonAddIndexRoute: typeof Authenticated_adminAdminDataPohonAddIndexRoute
  Authenticated_adminAdminMasterKodePatokBatasAddIndexRoute: typeof Authenticated_adminAdminMasterKodePatokBatasAddIndexRoute
  Authenticated_adminAdminMasterPohonLokalAddIndexRoute: typeof Authenticated_adminAdminMasterPohonLokalAddIndexRoute
  Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdIndexRoute: typeof Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdIndexRoute
  Authenticated_adminAdminConfigUserUserIdUpdateIndexRoute: typeof Authenticated_adminAdminConfigUserUserIdUpdateIndexRoute
  Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdCheckHistoryIndexRoute: typeof Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdCheckHistoryIndexRoute
  Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdUpdateIndexRoute: typeof Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdUpdateIndexRoute
  Authenticated_adminAdminDataPohonTreeIdSurveyHistoryIndexRoute: typeof Authenticated_adminAdminDataPohonTreeIdSurveyHistoryIndexRoute
  Authenticated_adminAdminDataPohonTreeIdUpdateIndexRoute: typeof Authenticated_adminAdminDataPohonTreeIdUpdateIndexRoute
  Authenticated_adminAdminMasterKodePatokBatasBoundaryMarkerCodeIdUpdateIndexRoute: typeof Authenticated_adminAdminMasterKodePatokBatasBoundaryMarkerCodeIdUpdateIndexRoute
  Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasIndexRoute: typeof Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasIndexRoute
  Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAllPhotosIndexRoute: typeof Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAllPhotosIndexRoute
  Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdUpdateKomunitasIndexRoute: typeof Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdUpdateKomunitasIndexRoute
  Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdCheckHistoryAddIndexRoute: typeof Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdCheckHistoryAddIndexRoute
  Authenticated_adminAdminDataPohonTreeIdSurveyHistoryAddIndexRoute: typeof Authenticated_adminAdminDataPohonTreeIdSurveyHistoryAddIndexRoute
  Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasAddIndexRoute: typeof Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasAddIndexRoute
  Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdCheckHistoryCheckBmHistoryIdUpdateIndexRoute: typeof Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdCheckHistoryCheckBmHistoryIdUpdateIndexRoute
  Authenticated_adminAdminDataPohonTreeIdSurveyHistorySurveyHistoryIdUpdateIndexRoute: typeof Authenticated_adminAdminDataPohonTreeIdSurveyHistorySurveyHistoryIdUpdateIndexRoute
  Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasGroupActivityIdUpdateIndexRoute: typeof Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasGroupActivityIdUpdateIndexRoute
}

const Authenticated_adminRouteChildren: Authenticated_adminRouteChildren = {
  Authenticated_adminAdminProfileRoute: Authenticated_adminAdminProfileRoute,
  Authenticated_adminAdminIndexRoute: Authenticated_adminAdminIndexRoute,
  Authenticated_adminAdminPemetaanIndexRoute:
    Authenticated_adminAdminPemetaanIndexRoute,
  Authenticated_adminAdminMasterPohonAddMasterTreeRoute:
    Authenticated_adminAdminMasterPohonAddMasterTreeRoute,
  Authenticated_adminAdminTentangKamiKelompokKomunitasAddKomunitasRoute:
    Authenticated_adminAdminTentangKamiKelompokKomunitasAddKomunitasRoute,
  Authenticated_adminAdminConfigRolePermissionIndexRoute:
    Authenticated_adminAdminConfigRolePermissionIndexRoute,
  Authenticated_adminAdminConfigUserIndexRoute:
    Authenticated_adminAdminConfigUserIndexRoute,
  Authenticated_adminAdminDataPatokBatasIndexRoute:
    Authenticated_adminAdminDataPatokBatasIndexRoute,
  Authenticated_adminAdminDataPohonIndexRoute:
    Authenticated_adminAdminDataPohonIndexRoute,
  Authenticated_adminAdminMasterKodePatokBatasIndexRoute:
    Authenticated_adminAdminMasterKodePatokBatasIndexRoute,
  Authenticated_adminAdminMasterPohonLokalIndexRoute:
    Authenticated_adminAdminMasterPohonLokalIndexRoute,
  Authenticated_adminAdminMasterPohonIndexRoute:
    Authenticated_adminAdminMasterPohonIndexRoute,
  Authenticated_adminAdminTentangKamiKelompokKomunitasIndexRoute:
    Authenticated_adminAdminTentangKamiKelompokKomunitasIndexRoute,
  Authenticated_adminAdminMasterPohonLokalUpdateMasterLocalTreeIdRoute:
    Authenticated_adminAdminMasterPohonLokalUpdateMasterLocalTreeIdRoute,
  Authenticated_adminAdminMasterPohonUpdateMasterTreeIdRoute:
    Authenticated_adminAdminMasterPohonUpdateMasterTreeIdRoute,
  Authenticated_adminAdminConfigUserAddIndexRoute:
    Authenticated_adminAdminConfigUserAddIndexRoute,
  Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdIndexRoute:
    Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdIndexRoute,
  Authenticated_adminAdminDataPatokBatasAddIndexRoute:
    Authenticated_adminAdminDataPatokBatasAddIndexRoute,
  Authenticated_adminAdminDataPohonTreeIdIndexRoute:
    Authenticated_adminAdminDataPohonTreeIdIndexRoute,
  Authenticated_adminAdminDataPohonAddIndexRoute:
    Authenticated_adminAdminDataPohonAddIndexRoute,
  Authenticated_adminAdminMasterKodePatokBatasAddIndexRoute:
    Authenticated_adminAdminMasterKodePatokBatasAddIndexRoute,
  Authenticated_adminAdminMasterPohonLokalAddIndexRoute:
    Authenticated_adminAdminMasterPohonLokalAddIndexRoute,
  Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdIndexRoute:
    Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdIndexRoute,
  Authenticated_adminAdminConfigUserUserIdUpdateIndexRoute:
    Authenticated_adminAdminConfigUserUserIdUpdateIndexRoute,
  Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdCheckHistoryIndexRoute:
    Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdCheckHistoryIndexRoute,
  Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdUpdateIndexRoute:
    Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdUpdateIndexRoute,
  Authenticated_adminAdminDataPohonTreeIdSurveyHistoryIndexRoute:
    Authenticated_adminAdminDataPohonTreeIdSurveyHistoryIndexRoute,
  Authenticated_adminAdminDataPohonTreeIdUpdateIndexRoute:
    Authenticated_adminAdminDataPohonTreeIdUpdateIndexRoute,
  Authenticated_adminAdminMasterKodePatokBatasBoundaryMarkerCodeIdUpdateIndexRoute:
    Authenticated_adminAdminMasterKodePatokBatasBoundaryMarkerCodeIdUpdateIndexRoute,
  Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasIndexRoute:
    Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasIndexRoute,
  Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAllPhotosIndexRoute:
    Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAllPhotosIndexRoute,
  Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdUpdateKomunitasIndexRoute:
    Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdUpdateKomunitasIndexRoute,
  Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdCheckHistoryAddIndexRoute:
    Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdCheckHistoryAddIndexRoute,
  Authenticated_adminAdminDataPohonTreeIdSurveyHistoryAddIndexRoute:
    Authenticated_adminAdminDataPohonTreeIdSurveyHistoryAddIndexRoute,
  Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasAddIndexRoute:
    Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasAddIndexRoute,
  Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdCheckHistoryCheckBmHistoryIdUpdateIndexRoute:
    Authenticated_adminAdminDataPatokBatasBoundaryMarkerIdCheckHistoryCheckBmHistoryIdUpdateIndexRoute,
  Authenticated_adminAdminDataPohonTreeIdSurveyHistorySurveyHistoryIdUpdateIndexRoute:
    Authenticated_adminAdminDataPohonTreeIdSurveyHistorySurveyHistoryIdUpdateIndexRoute,
  Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasGroupActivityIdUpdateIndexRoute:
    Authenticated_adminAdminTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasGroupActivityIdUpdateIndexRoute,
}

const Authenticated_adminRouteWithChildren =
  Authenticated_adminRoute._addFileChildren(Authenticated_adminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  Authenticated_adminRoute: Authenticated_adminRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  NotFoundRoute: NotFoundRoute,
  RegisterRoute: RegisterRoute,
  TentangKamiIndexRoute: TentangKamiIndexRoute,
  TentangKamiApaItuAdopsiPohonIndexRoute:
    TentangKamiApaItuAdopsiPohonIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
