export enum PERMISSION {
  USER_MANAGEMENT_VIEW = 'user-management.view',
  USER_MANAGEMENT_CREATE_LEVEL_GLOBAL = 'user-management.create-level-global',
  USER_MANAGEMENT_CREATE_LEVEL_GROUP = 'user-management.create-level-group',
  USER_MANAGEMENT_UPDATE_LEVEL_GLOBAL = 'user-management.update-level-global',
  USER_MANAGEMENT_UPDATE_LEVEL_GROUPT = 'user-management.update-level-group',
  ROLE_PERMISSION_MANAGEMENT_VIEW = 'role-permission-management.view',
  ROLE_PERMISSION_MANAGEMENT_CREATE = 'role-permission-management.create',
  ROLE_PERMISSION_MANAGEMENT_UPDATE = 'role-permission-management.update',
  COMUNITY_GROUP_CREATE = 'community-group.create',
  COMUNITY_GROUP_VIEW_LEVEL_GLOBAL = 'community-group.view-level-global',
  COMUNITY_GROUP_VIEW_LEVEL_GROUP = 'community-group.view-level-group',
  COMUNITY_GROUP_UPDATE_LEVEL_GLOBAL = 'community-group.update-level-global',
  COMUNITY_GROUP_UPDATE_LEVEL_GROUP = 'community-group.update-level-group',
  COMUNITY_GROUP_ACTIVITY_VIEW = 'community-group-activity.view',
  COMUNITY_GROUP_ACTIVITY_CREATE_LEVEL_GLOBAL = 'community-group-activity.create-level-global',
  COMUNITY_GROUP_ACTIVITY_CREATE_LEVEL_GROUP = 'community-group-activity.create-level-group',
  COMUNITY_GROUP_ACTIVITY_UPDATE_LEVEL_GLOBAL = 'community-group-activity.update-level-global',
  COMUNITY_GROUP_ACTIVITY_UPDATE_LEVEL_GROUP = 'community-group-activity.update-level-group',
  TREE_VIEW = 'tree.view',
  TREE_CREATE_LEVEL_GLOBAL = 'tree.create-level-global',
  TREE_CREATE_LEVEL_GROUP = 'tree.create-level-group',
  TREE_UPDATE_LEVEL_GLOBAL = 'tree.update-level-global',
  TREE_UPDATE_LEVEL_GROUP = 'tree.update-level-group',
}
